### ISSUE TITLE
1.1.0 Release

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10132]
Issue to manage 1.1.0 Release

### Release scope

- Changes: https://github.com/status-im/status-react/pulls?page=3&q=is%3Apr+merged%3A%3E2020-02-05
- Release notes: 
- Feature freeze date:  March, 4, 2019
- Expected release date: 

### Testing info
- build 1 test plan: https://ethstatus.testrail.net/index.php?/runs/view/4999
- build 2 test plan: https://ethstatus.testrail.net/index.php?/runs/view/5026&group_by=cases:section_id&group_order=asc

### Builds in TestFlight and PlayStore to push as a release
[RC 6](https://ci.status.im/job/status-react/job/release/job/release%252F1.1.x/6/): 
- https://status-im.ams3.digitaloceanspaces.com/StatusIm-200316-101036-7b64a9-release-universal.apk
- https://status-im.ams3.digitaloceanspaces.com/StatusIm-200316-101036-7b64a9-release.ipa

### Links for stable page update
Steps:

- [ ] Submit iOS build to Apple review
- [ ] Create release notes
Review needed: [release-notes-draft.txt](https://github.com/status-im/status-react/files/4329242/release-notes-draft.txt)

- [x] Regression testing for release candidate build
- [x]  (optional) Fix known blocker(s) found during regression testing
- [x]  (optional) Cherry pick fix(es) to the release branch
- [x] (optional) Verify fix(es) on new release candidate build
- [x] (optional) Retest
- [x] ~Battery consumption testing~
- [ ] Update description for final release build on PlayStore and AppStore
- [ ] Get links to release artefacts to update stable page
- [ ] Update status.im with Play Store, App Store and .apk links
- [ ] Get exact versions of the tested final release build from test team and push them as release

#### Fixes to cherrypick:
- [x]  #10130 - Disable playstore upload
- [x]  #10126 - Temporary fix for contacts signal
- [x]  #10146  - Use first-not-visible message instead of last-visible
- [x] #10159 - Unable to login to multiaccount if it is already restored as
- [x] #9987 - Improve watching to new blocks (recent transfers state) 
- [x] #10170 - Add billing permission android

#### Issues
- [x] #10133 Chat history is not shown after fetching ("Fetch more") until reopening chat
- [x] #10141 Unable to login to multiaccount if it is already restored as account in another multiaccount

Post release steps:

- [ ] Update PlayStore Screenshots if significant feature is added or existing Screenshots are no longer same as in previous version

**Comment by jakubgs** [comment]
I verified the [RC6 build](https://ci.status.im/job/status-react/job/release/job/release%2F1.1.x/6/) includes the billing permissions:
```
[nix-shell:~/work/status-react]$ apkanalyzer manifest permissions ~/StatusIm-200316-101036-7b64a9-release-universal.apk
android.permission.FOREGROUND_SERVICE
android.permission.VIBRATE
com.android.vending.BILLING
android.permission.NFC
android.permission.RECEIVE_BOOT_COMPLETED
android.permission.WRITE_EXTERNAL_STORAGE
android.permission.ACCESS_FINE_LOCATION
android.permission.INTERNET
android.permission.ACCESS_NETWORK_STATE
android.permission.WAKE_LOCK
android.permission.ACCESS_WIFI_STATE
android.permission.USE_FINGERPRINT
android.permission.CAMERA
android.permission.READ_EXTERNAL_STORAGE
```
