### ISSUE TITLE
Android app UI is slow when recieving new contacts every 30s

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10287]
# Bug Report
## Problem
Every 30s app freezes for a few seconds

#### Expected behavior
no freezes

### Additional Information
currently, we add all ens names from public chats to contacts object, that means there are can be thousands of contacts, also there are "dead" names that mean they never will be resolved, but we are still trying to resolve them each 30s, and send false result to status-react, this leads to heavy computations and UI is slow

* [x] do not react on contact's field not used in status-react #10317
* [x] process all contacts in one event #10317
* [x] do not resolve same names each 30s #10313

Below still critical not solved issue

* [ ] implement `ens-name-async` similiar to `identicon-async` do not add to contacts every user from chat (it takes ~10s to get contacts from app-db)
* [ ] optimize subscriptions #10381

https://drive.google.com/file/d/16F2oCn9zvVTUrsd68tFlJ95kaGb1fQlV/view?usp=sharing

**Comment by flexsurfer** [comment]
@cammellos, when you have time, would be great if you could help with the negative->positive in status-go

**Comment by churik** [comment]
@flexsurfer this one is relevant?

**Comment by flexsurfer** [comment]
yes

**Comment by cammellos** [comment]
seems like there's only one issue still open of the ones listed, so will close this one and keep the other open for, feel free to re-open if necessary
