### ISSUE TITLE
Send images > 6. Message actions and reply

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10475]
# Problem
As part of epic Send images, discussed in status-im/specs#69:

* [ ] 1. Write spec doc based on [this thread](https://github.com/status-im/specs/issues/69) #10417
* [ ] 2. Implementation image content type for chat messages status-im/specs#107
* [ ] 3. Implement image compression for message type (status-go) - OPTIONAL
* [ ] 4. Message sending and display #10474
* [ ] 5. UI for capture and image selection #9455
* [ ] **6. Message actions and reply :point_left:**
* [ ] 7. View images in user profile for 1:1 chats

## Implementation
Follow [Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=4190%3A25193) design

![Frame 53](https://user-images.githubusercontent.com/35233054/80704527-05f04e00-8ae5-11ea-8cf4-63e5c70db706.png)

- - -
![Frame 54](https://user-images.githubusercontent.com/35233054/80704531-07ba1180-8ae5-11ea-86fc-4e1d56a4d37a.png)

## Acceptance Criteria

* Implementation follows Figma
* User can reply to image
* User can copy image and paste in text input field

## Future Steps

1. View images in user profile for 1:1 chats
