### ISSUE TITLE
Add Status logo/styling to QR code

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10627]
# Problem
Chat (key) QR code is intended to easily invite others to join you on Status. Allowing users to share the QR code wherever they want (e.g. social media, website, slidedeck) can increase acquisition. Currently, the QR code is not suited for use outside the app and status.im; It shows no context of what the QR code would do (e.g. download and deeplink to user or chat), nor communicates that it relates to Status.

## Implementation
Following #10325 (request compressed key to generate simplified QR code)

#### Core app

* Profile QR (visible in app> `Profile`, other user `Share`)
* Group chat QR https://github.com/status-im/status-react/issues/10179

### TODO's

* [ ] Design update to include a variation that does not rely on ENS profile image (i.e. user does not have an ENS name), QR is for a public channel or group chat
* [ ] Request compressed key for Profile QR from status-go. See #10325 if it makes sense to implement a function in status-react first
* [ ] Apply styling to compressed key using QR code library. Designs on [Figma ](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=2869%3A23223). Please ping @errorists to check for any updates

![QR code styling](https://user-images.githubusercontent.com/35233054/81682856-8ef87500-9455-11ea-96f2-316f277b16ae.png)

## Acceptance Criteria
Follow designs on [Figma ](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=2869%3A23223)

## Future Steps
QR code styling should also be applied on join.status.im in separate issue on https://github.com/status-im/universal-links-handler/

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
