### ISSUE TITLE
Components finalisation [EPIC]

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#12053]
Current state of components inmplementation

component | status-im.ui | usage | descr | quo | usage | descr
-- | -- | -- | -- | -- | -- | --
colors | status-im.ui.components.colors | 50% |   | quo.design-system.colors | 50% | used by quo components
typography | status-im.ui.components.typography | 112 occurr. | used by react/text | - |   | no typography?
text | status-im.ui.components.react/text | 75% |   | text | 25% |  
text-input | status-im.ui.components.react/text-input | 6 occurr. |   | text-input | 60 occurr. |  
icons | status-im.ui.components.icons.vector-icons | 100% |   | - |   |  
list-header | probably there are custom implementations in the code |   |   | list-header | 23 occurr. |  
list-item | status-im.ui.components.list.views/item | 4 occurr. |   | list-item | 190 occurr. |  
topbar | status-im.ui.components.topbar | 92 occurr. | uses quo.header | header | 2 occurr. | used by ui/topbar
button | probably there are custom implementations in the code |   |   | button | 133 occurr. |  
tooltip | status-im.ui.components.tooltip.views | 4 occurr. |   | tooltip | no usage | prbably not finished
toolbar | status-im.ui.components.toolbar | 40 occurr. |   | - |   |  
popover | status-im.ui.screens.popover.views |   |   |   |   |  
bottom sheet |   |   |   | bottom-sheet |   |  
  |   |   |   | switch |   | used by quo components
radio | status-im.ui.components.radio | 4 occurr. |   | radio |   | used by quo components
  |   |   |   | checkbox |   | used by quo components

- [x] - 1) move colors to quo https://github.com/status-im/status-react/issues/12047
- [ ] - 2) replace react/text usage https://github.com/status-im/status-react/issues/12048
- [ ] - 3) move icons https://github.com/status-im/status-react/issues/12049
- [x] - 4) list-item https://github.com/status-im/status-react/issues/12050
- [ ] - 5) toolbar https://github.com/status-im/status-react/issues/12051
- [x] - 6) radio https://github.com/status-im/status-react/issues/12052

**Comment by churik** [comment]
@flexsurfer does it make sense in terms of new component library?
