### ISSUE TITLE
Upgrade React Native to latest version

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#13102]
### Tasks
- [ ] Upgrade React Native
- [x] Remove `"hermes-engine": "0.5.2-rc1"` [Comment](https://github.com/status-im/status-react/pull/13028#discussion_r796932113) (Removed in https://github.com/status-im/status-react/pull/13360)
- [ ] use same speed for both android and ios draggable-flat-list [Comment](https://github.com/status-im/status-react/blob/36c7d8e4ca2a41317778306a12aff8023163e3a2/src/status_im/ui/screens/communities/reorder_categories.cljs#L143)
- [ ] remove 50 when react-native-navigation v8 will be implemented [Comment](https://github.com/status-im/status-react/blob/36c7d8e4ca2a41317778306a12aff8023163e3a2/src/quo/components/bottom_sheet/view.cljs#L44)

**Comment by Parveshdhull** [comment]
outdated
