### ISSUE TITLE
Implement “Delete for me” option for messages

### ISSUE THREAD

**Issue by briansztamfater** [status-im/status-react#13873]
# Feature Issue

### User Story

As a user, I want to delete messages locally **so that** I can remove message I don't want to see without removing them to the other chat participants. 

### Description

Flow TBD

### Acceptance Criteria

TBD

### Notes

Link to Message Context Drawer in Figma: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4388%3A631636

<img width="275" src="https://user-images.githubusercontent.com/18485527/187117579-9c0bebe4-3633-4cf5-a8ea-938e92bca472.png">

**Comment by yqrashawn** [comment]
deleted for me messages ~https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments?node-id=4136%3A421265~
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=5713%3A624211

**Comment by yqrashawn** [comment]
- [x] menu UI #14007 
- [x] deleted message UI (using system message component) #14168
- [x] deleted for me notification with undo UI, waiting on toast component https://github.com/status-im/status-mobile/issues/13831
- [x] delete/undo logic #14007
- [x] status-go https://github.com/status-im/status-go/pull/2866 (version 0.111.1 already included in status-mobile)
- [x] temp UI indicating message deleted for me (deleted for me messages have a red border)

**Comment by yqrashawn** [comment]
completed in https://github.com/status-im/status-mobile/pull/14618
