### ISSUE TITLE
Mobile release 1.20

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13880]
Issue to manage mobile release 1.20

### Scope
[comment]: # (Add milestone from github)
https://github.com/status-im/status-mobile/milestone/59

- release notes: https://github.com/status-im/status-mobile/blob/327d456f696d817663259636cedaed50513cd28d/RELEASES.md 1.20;
- release branch: https://github.com/status-im/status-mobile/tree/release/1.20.x
- release build: https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F1.20.x/

### Testing info 
[comment]: # (TestRail info, added by QA)
Main test suite: https://ethstatus.testrail.net/index.php?/runs/view/9921

### Builds in TestFlight and PlayStore to push as a release
[comment]: # (Will be added by QA after testing approving of build)

#### 1) Kick-off
- [x] 1. Translation PRs is merged before cutting branch (Jinho) https://github.com/status-im/status-mobile/pull/13729
- [x] 2. Prepare scope of visible changes based on commits history, started from previous release branch cut ([guide](https://notes.status.im/how-to-prepare-release-notes))
- [x] 3. Update [RELEASES.md](https://github.com/status-im/status-mobile/blob/develop/RELEASES.md) with release notes (make PR based on previous step)
- [x] 4. Create release branch using this [guide](https://github.com/status-im/status-mobile/blob/develop/doc/RELEASE_GUIDE.md), bump VERSION (merge created PR ([example](https://github.com/status-im/status-mobile/pull/12504) ) to develop) and get successful release builds (so, testing can be started)
- [x] 5. Based on release scope, ask for comms (Jonny) 
- [x] 6. Make sure that assets (screenshots, video) in stores are up-to-date, more info [here](https://notes.status.im/how-to-update-assets)

#### 2) Testing
[comment]: # (Section will be maintained by QA)
- [x] Dogfooding (add notes, if it was held) 
- [x] Regression testing for release candidate build
- [x] Upgrade tests
- [x] Fix known blocker(s) found during regression testing

##### Blockers
[comment]: # (Section for blocker issues; should be fixed and merged by release-manager. Remove if no blockers found)
- [x] #13887
- [x] #13889
- [x] #13891 
- [x] #13892
- [x] #13914
- [x] #13916 
- [x] #13956
- [x] #13955 
- [x] #13957 
- [x] #14009

============================================================================================

##### Fixes (cherry-pick)
- [x] #13901
- [x] #13897 
- [x] #13898
- [x] #13889 fix in https://github.com/status-im/status-mobile/commit/896ce9507af6c620012ff66136ac3fa1c3cb45da
- [x] IOS fixes in https://github.com/status-im/status-mobile/commit/1e37ff91db46b600f00391bd14dc715bfc405b85 and https://github.com/status-im/status-mobile/commit/5487868078243b70cc41109fc8728cb198d9659a
- [x] #13881 (not a blocker, but relevant fix)
- [x] #13902 (not a blocker, but relevant fix)
- [x] #13924 (not a blocker, but relevant fix)
- [x] https://github.com/status-im/status-go/pull/2837 fix for #13916 
- [x] #13938
- [x] #13944 

============================================================================================
- [x] Verify fix(es) on new release candidate build
- [x] Retest
- [x] Keep release build forever (button in Jenkins)

#### 3) Submission

- [x] 1. Prepare PR for F-droid build ([instruction]( https://github.com/status-im/status-mobile/blob/develop/doc/FDROID.md))
- [ ] 2. Release notes written and added (500 character limit for updates (Android) and PR for [RELEASES.md](https://github.com/status-im/status-mobile/blob/develop/RELEASES.md) is ready to be merged (from 1.3 step)
- [ ] 3. Submit beta version for Android (Open Testing in Play Store)
- [ ] 4. Submit iOS build to Apple review ([instruction](https://drive.google.com/file/d/10Cl7PBB7TFPkZiVbfzdFGpfMRP9bxXuq/view?usp=sharing), be careful - low quality of audio)
- [ ] 5. Play store content reviewed and updated
- [ ] 6. Privacy policy reviewed and updated (ask in channel)
- [ ] 7. Countries to be excluded (ask in channel) 
- [ ] 8. Changes to our FAQ made (should be checked and if any changes needed, ask Jakub to made them)

#### 4) Before publishing
- [ ] 1. Translations for comms available (marketing, ask in the channel)
- [ ] 2. Promotional content ready (marketing, ask in channel)
- [ ] 3. Upload builds for DO store,  https://dev.status.im/ (Jakub)

#### 5) At time of publishing
- [ ] 1. Notify marketing to push comms and blog post (Jonny + get review on blog from QA team)
- [ ] 2. Publish release to app store and playstore
- [ ] 3. Final push to update prod site https://status.im/,  [instructions](https://github.com/status-im/infra-docs/blob/master/articles/status_release_upload.md) (Jakub - requires credentials to upload) 
- [ ] 4. Add the link to the post about the release and publish the release: https://github.com/status-im/status-mobile/releases (Jakub)
- [x] 5. Merge PR for updating [RELEASES.md](https://github.com/status-im/status-mobile/blob/develop/RELEASES.md) (from 1.3 step)

**Comment by flexsurfer** [comment]
Fdroid PR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11770
