### ISSUE TITLE
Network Switching (status-react)

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1511]

**Comment by asemiankevich** [comment]
current tasks for Network Switching feature:

- [x] add main net warning - revisit with the wallet squad and @denis-sharypin #2096 
- [x] add network title to the Connect screen #2102 
- [x] add alert with text that user will need to login again after the network is switched (can we combine this message with the restart message and don’t display 2 alerts in the row?) #2103
- [x] remove buttons that are not implemented - `Add network` and `Edit network config` #2104

Nice to have:
- [ ] format the JSON code with the network configuration
