### ISSUE TITLE
Wallet design - Main screen

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1523]
### User Story

As a user, I want to access the wallet and that I check the total market value of the assets. 

#### Acceptance

- [x] I can access the wallet by tapping the Wallet tab
- [x] I can see the current recent total market value of the ETH balance
- [x] I can refresh the wallet total value and the assets by pull-to-refresh gesture
- [x] I can see the ETH balance of the default account
- [x] I can see the error message when something goes wrong

Outbound flows should be presented but not required to be implemented in the scope if this issue (each flow will have its own acceptance):
- [x] I can access the wallet's assets list
- [x] I can access transactions history
- [x] I can access the wallet command to:
- Scan/Share QR
- Wallet Settings
- Manage Assets
- Add Asset
- [x] I can open the side menu
- [x] I can access transactions history
- [x] I can change the wallet (select another wallet)
- [x] I can send a transaction
- [x] I can request a transaction
- [x] I can see that I can exchange when it's implemented
- [x] I can access the other tabs such as Chat, Discover, and Contacts

**Comment by GustavoNunes** [comment]
### Todo:
- [x] Basic main screen implementation (styles, hardcoded data)
- [x] Basic wallet list implementation (styles, hardcoded data)
- [ ] UI (waiting for design to be completed)
  - [ ] Correct colors, exact font sizes, positioning, etc.
  - [ ] Add icons (both regular and asset icons)
  - [ ] Change background color of different wallets 
  - [ ] i18n strings
- [ ] Navigation (rework main tabs, add toolbars and navigation handlers)
- [ ] Dynamic data
  - [ ] Design app-db, create sample data, specs, handlers and subs
  - [ ] Fetch real data from blockchain

**Comment by sla-shi** [comment]
@sla-shi to open a data binding issue to follow up this task.

**Comment by denis-sharypin** [comment]
@GustavoNunes Hey, you can find all UI regarding a main Wallet screen here zpl://screen?pid=5863cdcee68455850f1929f2&sid=5991fb488fea42dc85f90b5e

**Comment by jeluard** [comment]
Missing:

* data binding with real wallet

**Comment by jeluard** [comment]
Fixed in develop
