### ISSUE TITLE
Wallet design - Send Transaction

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1525]
### User Story

As a user, I want to Send transaction from the wallet and specify recipient, amount and other details. 

#### Acceptance

- [x] I can start the Send transaction flow by tapping the Send button on the wallet main screen #1773 

- [x] I can specify the recipient by scanning the QR code
- [x] I can specify the recipient by choosing from app Contacts (that have wallet address) #1843 
- [x] I can specify the recipient by using address from Clipboard #1773 
- [ ] I can specify the recipient by using the QR code from Gallery
- [x] I can enable camera and gallery access when needed

- [x] I can specify the amount to send #1843 

- [x] I can overview basic details - the wallet to send from, the amount, and the target address #1843 
- [x] I can sign the transaction with my password 
- [x] I can recognize the 3 words from my onboarding experience when I sign the transaction #1585 
- [x] I can receive notifications about corner cases such as Not enough fund, or Wrong password

Not in scope - should be presented but not required to be implemented in the scope if this issue (each item will have a separate issue):
- [ ] I can't select currency (only ETH)
- [ ] I can't select the wallet to send from
- [ ] I can't overview advanced details of the transaction - tx fee, data and block number

**Comment by sla-shi** [comment]
@sla-shi to create the binding Issue.

**Comment by denis-sharypin** [comment]
UI is here zpl://screen?pid=5863cdcee68455850f1929f2&sid=5991fb3a0f0692af9117d1ee

**Comment by x-goose-x** [comment]
* Choose Recipient Screen
- [ ] Create and style
- [ ] Add QR scanning functionality
- [ ] Add contact screen picker
- [ ] Add contact editor
- [ ] Add clipboard editor
- [ ] Scan QR from file browser
* Camera permission view
- [ ] Grant camera position (ios)
* Send transaction screen
- [ ] Create Screen
* Wallet picker screen
- [ ] Create screen
* Currency Picker Screen
- [ ] Create screen (depends on asset data binding)
* Send Transaction Confirmation Screen
- [ ] Create screen
- [ ] Handle insuff. funds
- [ ] Handle wrong password
** Send transaction advanced screen
- [ ] Render advanced data
** Handle transaction cancellation flow
- [ ] Create cancellation prompt

**Comment by annadanchenko** [comment]
Functional description (WIP) for one of the minimal flows for Send transaction: https://docs.google.com/document/d/13eItUUqlfkRpx7iSutPRvThzTSrhirnKBcgxhOD3m6g

**Comment by asemiankevich** [comment]
Moving to tested with the reference to https://github.com/status-im/status-react/issues/584#issuecomment-329427213

**Comment by flexsurfer** [comment]
Fixed in develop, will be in release 0.9.12
