### ISSUE TITLE
Design notes: I'm new to status screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15780]
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1902-145290&t=IygHPkoLwgiVR8Xa-4)

## Expected fixes

- [ ] Old icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1902:145290#427971898))
- [x] "Experienced in Web3?" missing label (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1902:145290#427972159))
- [x] Flickering white between  "I'm new" > "Generate keys" transition (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1902:145290#427993559))

https://user-images.githubusercontent.com/4557972/235438903-7c5cd7d9-f87e-407e-b040-477e586721f7.mp4

- [x] Change transition between full screens to transition between content (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1902:145290#427994436))

**Comment by siddarthkay** [comment]
> * Change transition between full screens to transition between content

Hmm so the design team expectation is for there to be a swiper or a slider component in place 🤔
I wonder what are the performance implications of such a component/UI @flexsurfer @ilmotta @J-Son89

**Comment by flexsurfer** [comment]
`Flickering white between "I'm new" > "Generate keys" transition ` is general problem, better to have a separate issue for it

**Comment by ilmotta** [comment]
> > * Change transition between full screens to transition between content
> 
> Hmm so the design team expectation is for there to be a swiper or a slider component in place thinking I wonder what are the performance implications of such a component/UI @flexsurfer @ilmotta @J-Son89

Good question @siddarthkay. My guess is we can achieve the design requirements if we manage to render only one step at a time and maybe just the next one (not all steps) to have a smooth transition.

Hard to say without trying some things, but I'm thinking about a FlatList where we can explicitly control how many elements (steps) should be rendered and maybe use `InteractionManager.runAfterInteractions` to sort of "pre-render" certain steps when we know the user is "done" with the current one.

Or maybe none of this is necessary and it'll just work fine without much optimization?

**Comment by J-Son89** [comment]
I'm curious whether the package we use can handle custom transitions and if not is there a better navigation package we can upgrade to which will simplify this whole process. Perhaps better to have this discussion on the focused issue @flexsurfer surfer mentioned we should create.

**Comment by J-Son89** [comment]
@flexsurfer did we create a separate issue yet for the transition? If not I can create this issue now.

**Comment by flexsurfer** [comment]
i'm not aware of any, cc @churik

**Comment by J-Son89** [comment]
ok, I have created one: https://github.com/status-im/status-mobile/issues/15877

**Comment by J-Son89** [comment]
icon is fixed here: https://github.com/status-im/status-mobile/pull/15863#pullrequestreview-1422638570

**Comment by J-Son89** [comment]
@churik - I have fixed missing label here:
https://github.com/status-im/status-mobile/pull/15876

icon is fixed https://github.com/status-im/status-mobile/pull/15863#pullrequestreview-1422638570

and the transition issue I have moved to a common issue as we agreed in this issue: https://github.com/status-im/status-mobile/issues/15877

Should we close this Issue? 🤔

**Comment by flexsurfer** [comment]
Flickering white between "I'm new" > "Generate keys" transition is fixed
