### ISSUE TITLE
Design notes: communities home

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15785]
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1926-135773&t=IygHPkoLwgiVR8Xa-4)

## Expected fixes

- [x] Add accent color to required components  (jump to, user avatar, + )
- [x] Update tabs icons (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428397631))

### User avatar
- [ ] Add identicon ring (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428395871))
- [ ] Photo avatar if avatar is present (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428391389))
- [x] Accent color if no avatar is set(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428391389))
- [x]  Check online indicator mark (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428396527))

### Top bar icons
- [x] Scan QR icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428394068))
- [x] Notification bell icon  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428395257)) 

### Discover
- [x] Update copy (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428395364))
- [x]  Check shadow (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428393826))
- [x]  Check tabs background color (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428394418)) 
- [x]  Add empty state (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135772#428395620))
