### ISSUE TITLE
Design notes: generate keys flow > profile name screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15781]
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1908-165988&t=IygHPkoLwgiVR8Xa-4)

### Profile name
- [ ] Change paddings (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428217503))
- [ ] Check avatar size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428005167))
- [ ]  Check initial text size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428005420))
- [ ] Align photo icon to the avatar (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428006053))
- [ ]  Make edit box focused by default with opened keyboard (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428007727)) 
- [ ] "Name" shouldn't start with a capital letter (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428008049))
- [ ]  Check font size of placeholder(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428217177))
- [ ]  Medium font size for "Accent colour"(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428011481)) 
- [ ]  Change the background according to design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428189441)) 

### Avatar drawer

- [ ]  Check icon design/size (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428200533)) 
- [ ]  Check drawer background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428203070)) 

### Profile name - errors
- [ ]  "Special chars are not allowed" - Check size, design, distance to the text.... (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428266752)) 
- [ ]  Flickering screen on focus (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1908:165988#428273559)) 
Video (slowed down 1/4X)

https://user-images.githubusercontent.com/4557972/235442939-54820d73-062d-459e-a9dd-5ef9b7b1036a.mp4

**Comment by J-Son89** [comment]
also see https://github.com/status-im/status-mobile/issues/16067
