### ISSUE TITLE
Design notes: app locked

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15788]
### Enter password screen

- [x] #15853
- [ ] Check input top padding (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147125#429504774))
- [ ] Check background(full comment [here][(https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429121577](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147125#429507964))

#### PR(https://github.com/status-im/status-mobile/pull/15927) with fixes for the following:
- [x] Update design "Forgot password" (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147125#429505201))
- [x] Update login button design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147125#429513108))
- [x] Update "Wrong password"  error design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147125#429524054) and [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147125#429523918))

### Splash screen
- [ ] Flickering white screen on splash  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147125#429541716))

**Comment by yqrashawn** [comment]
@ajayesivan mind I work on the first one?

**Comment by ajayesivan** [comment]
> @ajayesivan mind I work on the first one?

Sure, that's fine. Feel free to work on that.
