### ISSUE TITLE
Design notes: generate keys flow > leftovers (animation, notifications, welcome screen, biometric)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15784]
### Biometrics (designer comments [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1926-130706&t=IygHPkoLwgiVR8Xa-4)

- [ ] Remove navigation (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:130706#428375838))
- [ ] Check the background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:130706#428382677))
- [ ]  Update illustration (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:130706#428375917))
- [ ] Update icon design for "Face id" icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:130706#429200265))
- [ ] Change button color (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:130706#428376239))

### Generating keys carousel

Still in the review process. Will be added later

### Notifications
- [ ] Distance between title and text below  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:134809#429226144))
- [ ]  Update text (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:134809#429226282))
- [ ]  Update illustration (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:134809#428386146))
- [ ]   Update icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:134809#429199828))

### Welcome and theme selection
- [ ]  Check background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1926:135347#428387520))

**Comment by churik** [comment]
Doesn't make sense anymore
