### ISSUE TITLE
Design notes: switch profiles

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15789]
### Profiles screen

- [ ] Update background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429588455))
- [ ] Add drop shadow on profile cards (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429588832))
- [x] #15793
- [ ] Check background when scrolling profiles list(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429596823))
- [ ] Add animation on transition between profiles (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#430251047) and video [here](https://drive.google.com/file/d/1YdO-oM5tB2rvw3sACQMrC2x8x2FqjNQk/view))

### Profile options
- [x] Check drawer background color (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429599916))
- [x] Update icon design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429600285))
- [x] Check bottom padding (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429600816))

### Delete drawer
- [ ] Context tag should be blur (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429604793))
- [ ] Button should be blur (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429604968))

### Add new profile
- [x] Update icons (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429603184))

**Comment by cammellos** [comment]
Update background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429588455))
 Add drop shadow on profile cards (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429588832))

@Parveshdhull I believe you did some investigation on those, and as I understand, they are technically quite complex, is that the case?

Thanks

**Comment by cammellos** [comment]
> Update icon design (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429600285))
 Check bottom padding (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429600816))

These are small fixes

**Comment by cammellos** [comment]
A lot of these issues have to do with blur, make sure you prioritize lower hanging fruits, if blur is causing issues

**Comment by Parveshdhull** [comment]
> Update background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429588455))
> Add drop shadow on profile cards (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1946:147656#429588832))

> @Parveshdhull I believe you did some investigation on those, and as I understand, they are technically quite complex, is that the case?

Yes,
- update background - by default library doesn't support transparent blur type([ref](https://github.com/status-im/status-mobile/pull/14783#discussion_r1084603578)), and for supporting that we are using patch provided in [#513](https://github.com/Kureev/react-native-blur/pull/513) pr, but this solution also creates a [blue overlay](https://github.com/Kureev/react-native-blur/pull/513#issuecomment-1399026306) side effect
- drop shadow - Most of props related to drop shadow are only [available](https://reactnative.dev/docs/shadow-props) for ios, so we are currently not able to show drop shadow in android. Also, for ios use of drop shadow is creating this weird square edges as mentioned in last section of [issue 3](https://github.com/status-im/status-mobile/pull/15376#issuecomment-1476089275) comment. (maybe because we use this with hole-view)

**Comment by J-Son89** [comment]
@ajayesivan has handled the old/new icons issue here - https://github.com/status-im/status-mobile/pull/15937 so we can remove that as a requirement of this issue?
