### ISSUE TITLE
Design notes: sign in by syncing

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15787]
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1929-154137&t=IygHPkoLwgiVR8Xa-4)

### Empty state

- [x] Update icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429151296))
- [x] Update tabs color (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429121879))
- [x] Update tabs color (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429121879))
- [x] Update dash line border (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429121577))
- [x] Update icon "Enable camera" (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429120707))
- [x] Update color "Enable camera" (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429121021))
- [x] Update background  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429120328))
- [x] Update font size  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429147530))

### Camera access
- [x] Update back nav(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429210625))
- [x] Check borders design(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429224561))
- [ ] Add flash option (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429186829))

### Syncing devices
- [x] Remove navigation (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429189482))
- [ ] Add illustration  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1929:154137#429189321))

**Comment by qoqobolo** [comment]
@jo-mut can you please review the issue and check what has been already done?
Asking about it because for example `Remove navigation` is already done judging by your comment in Figma but it's not ticked here
<img width="565" alt="Screenshot 2023-06-01 at 16 06 10" src="https://github.com/status-im/status-mobile/assets/67952253/7c255f1b-f1d6-4295-aadc-ace4dd187f29">
