### ISSUE TITLE
Design notes: generate keys flow > Password screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15783]
## Problem 
Suggestions/issues on implementation in Figma are [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?node-id=1922-172632&t=IygHPkoLwgiVR8Xa-4)

### First step
- [ ] Active first input with  opened keyboard (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428342839))
- [ ] Update "eye" icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428346840))
- [ ]  Update icon "Min 10 chars" (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428343023))
- [ ] Update background (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#429038637))

### Security tips
- [ ]  Fix keyboard overlapping with "Confirm password"(full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428356533))
- [ ]  "I understand my password can't be recovered" should appear only when passwords match (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428356770))

### Errors
- [ ]  Update icon (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428370344))

### Disclaimer
- [ ]  Checkbox white/black (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=1922:172632#428375016))

**Comment by pavloburykh** [comment]
@smohamedjavid thanx for the PR! Please, take a look at the following issues. 

### ISSUE 1 Disclaimer overlays password field/passwords match info message

**Screenshot from iPhone X:**

![photo_2023-05-12 11 55 02](https://github.com/status-im/status-mobile/assets/97245802/8507f745-0107-473f-a96a-52c796b1f983)

**Screenshot from iPhone SE:**

![photo_2023-05-12 11 55 47](https://github.com/status-im/status-mobile/assets/97245802/73b9544d-75fc-46c3-8e23-8f1ed086f8cb)

**Screenshot from Samsung Galaxy A52:** disclaimer is sticked to "Passwords match" info message

![photo_2023-05-12 11 58 16](https://github.com/status-im/status-mobile/assets/97245802/011c4faa-3bdb-4159-8cce-d885232c1b5c)
