### ISSUE TITLE
Design review: community banner animation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16788]
- [ ] Add more margin to align profile avatar with 'communities' title (more details [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3645:332235&mode=design#508982651))
- [ ] Add more margin to tabs with 'communities' title (more details [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3645:332235&mode=design#508980947))
- [ ] Make a community banner longer (more details [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3645:332235&mode=design#508980481))
- [ ] Make "Communities" title and [+] button icon bigger (more details [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3645:332235&mode=design#508981720))

**Comment by ilmotta** [comment]
Closing as _not planned_ because animation work is currently descoped.
