### ISSUE TITLE
Wrong UI on the top bar (design review)

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16782]
- [x] Add more space between 'back' button and user avatar picture  (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507797774))
- [x] Change the font for online/offline status mark (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507795612))
- [x] Add "offline" status when a user is offline (full comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3614:306079&mode=design#507812461))

### Additional Information
Status version: nightly
Operating System: Android, iOS
