### ISSUE TITLE
Design review: communities home

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16846]
- [ ] 1. Joined, Pending, Opened looks smaller than at designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510253373)  
- [ ] 2. `Discover` there's a stroke and the shadow is missing **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254368)  

- [ ] 3. Glow in Communities is almost like a shadow around the titles in white mode **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254973)  

- [ ] 4. Spacing between communities in the list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258492)  
- [ ] 5. The unread indicator dot looks bigger than in the designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258717)

**Comment by churik** [comment]
Community banner anomation issues are logged sparately in https://github.com/status-im/status-mobile/issues/16788

**Comment by cammellos** [comment]
1,4,5 small issues, 1.25
2, 3 looks like they could be a bit more involved

**Comment by mohsen-ghafouri** [comment]
* [X]  1. Joined, Pending, Opened looks smaller than at designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510253373)
* [X]  2. `Discover` there's a stroke and the shadow is missing **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254368)
* [X]  4. Spacing between communities in the list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258492)
* [X]  5. The unread indicator dot looks bigger than in the designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511258717)

this point is related to blur issue, should be handled separately
* [ ]  3. Glow in Communities is almost like a shadow around the titles in white mode **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254973)

**Comment by mohsen-ghafouri** [comment]
This [PR](https://github.com/status-im/status-mobile/pull/17097) should resolve this :

* [X]  3. Glow in Communities is almost like a shadow around the titles in white mode **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511254973)
