### ISSUE TITLE
Design review: community page

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16849]
- [ ] 1. Scrolling down - all the page comes down and the Community profile pic increses size-  **(IOS only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510052006)  
- [ ] 2. Margins between community tags and community channels  - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510230411)  
- [ ] 3. Joined icon is smaller - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511270028)  
- [ ] 4. Closed button blur is too subtle - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511270826)  
- [ ] 6. Avatar is too big and not aligned - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511268171)

**Comment by cammellos** [comment]
2, 3, 6 looks like small issues, 1.25

4 could also be, but blur has been problematic before
1 not sure, requires further investigation

**Comment by cammellos** [comment]
@alwx could you create a separate issue on those you are working on and unassign yourself from the whole issue? (unless you are actually working on all the points together)

**Comment by alwx** [comment]
I'm working on them all together except maybe number 1 because it seems too complicated. Will update this issue later today based on my investigation.

**Comment by alwx** [comment]
The community screen has been changed and requires a new review now because it looks very different to what was reviewed. For example, the icon doesn't go up any longer, there is no description and icons. This is how it all currently looks:

<img width="564" alt="Screenshot 2023-09-14 at 16 19 43" src="https://github.com/status-im/status-mobile/assets/911127/873f7232-cda0-44c8-aa21-d6fc8e043bbc">

**Comment by churik** [comment]
Closing this in favor of [ 1.25 ](https://github.com/status-im/status-mobile/issues?q=is%3Aopen+is%3Aissue+label%3A%22E%3ADesign+Feedback+1.25%22)
