### ISSUE TITLE
Design review: activity centre

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16841]
- [ ] 1. Dot is overlapping with the timestamp on "Request hasn't been accepted" notification - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510053049)  
- [ ] 2. Spacing in AC notifications doesn't match the design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510052712)

- [ ] 3.  on the `Accepted` label status tag padding is different from design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#511248488)
- [ ] 4. wrong spacing in contact request AC notification between username and text - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#511247483)
- [ ] 5. No blur on the bottom drawer  comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510053488) 
suppose it might be a part of https://github.com/status-im/status-mobile/issues/15513 or https://github.com/status-im/status-mobile/issues/16722 (just an assumption, not sure)

**Comment by smohamedjavid** [comment]
> 1. Dot is overlapping with the timestamp on "Request hasn't been accepted" notification - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:328391&mode=design#510053049)

No design reference for it. https://github.com/status-im/status-mobile/issues/15768

**Comment by cammellos** [comment]
1 as per @smohamedjavid, we need a design reference I believe @Francesca-G @pedro-et 

2, 3, 4 looks like small/medium, 1.25

5 as it touches blur and bottom drawer I defer to @flexsurfer

**Comment by pedro-et** [comment]
@cammellos refernece in the designs already :)

**Comment by cammellos** [comment]
@pedro-et thanks!

**Comment by cammellos** [comment]
@smohamedjavid it has been added in the system design reference file https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1578-34575&mode=design&t=MxlL05YCAl41bl2I-0 , Notifications -> along 2 lines

so 1 is also ok for 1.25, medium effort looks like

**Comment by BalogunofAfrica** [comment]
Added these based on @Francesca-G's review

- [ ] 6. Text isn't centred in the decline/accept buttons - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=4909:50437&mode=design#538594339)  
- [ ] 7. Customization colors in shell theme are the dark theme ones (orange/60 in this case)- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=4909:50437&mode=design#538599185)
