### ISSUE TITLE
Design review: community channel (chat view)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16859]
- [X] 1. `Deleted` icon is  too small in "Message deleted" - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511286027)  #17108
- [X] 2. No hashtag in channel name- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510271859) ,#17187
- [X] 3. Wrong bg color for system messages  - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510273990)  ,#17187
- [x] 4.1 Jump to button spacing is different from design- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511270826), https://github.com/status-im/status-mobile/issues/16887
- [x] 4.2 Also there are other issues with Jump to button in chat view, i.e. https://github.com/status-im/status-mobile/issues/16331
- [x] #17027

**Comment by cammellos** [comment]
1, 2, 3 are small issues 1.25
5 a bit larger, still good to have in 1.25

4 looks like it could be a bit more involved, maybe @Parveshdhull can share his opinion

**Comment by Parveshdhull** [comment]
Spacing of jump-to should be fairly easy to fix. (I will do that)
Behavior of jump-to button position while scrolling probably covered under top bar issues (As scrolling is handled there).
Not sure about complexity  @alwx will know better.

**Comment by alwx** [comment]
4 is tricky — I tried several options and several ways of setting offsets when scrolling, sadly none of them helped :(

**Comment by yqrashawn** [comment]
issue 1 caused by inconsistent in figma, question posted [here](https://discord.com/channels/624634427930312714/975775548007678033/1144166300084605039)

**Comment by mohsen-ghafouri** [comment]
I think just 2,3 are left for this issue, i'm going to work on them.

**Comment by mohsen-ghafouri** [comment]
@yqrashawn is the sub issue 1 resolved?

**Comment by yqrashawn** [comment]
> @yqrashawn is the sub issue 1 resolved?

yes, sub issue 1 resolved in https://github.com/status-im/status-mobile/pull/17108
