### ISSUE TITLE
Design review: messages home

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16864]
- [ ] 1. Date and hour are not aligned in chats list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511309210)  
- [ ] 2. Wrong margin between list items - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510226396)  
- [ ] 3. The badge is not aligned with  date and hour  and name - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306952)  
- [ ] 4. Unread barge may overlap with text and not aligned to design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306759) 
![image](https://github.com/status-im/status-mobile/assets/4557972/2bcfe7fe-cac5-4178-8f7e-b8163b5edbd7)

- [ ] 5. Missing counter border - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510044277)  
- [ ] 6. + uses outdated color - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510043895)  
- [ ] 7. Unmute icon may overlap with date - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510042990)  
- [ ] 8. When user set nickname, their real name is not shown anymore - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#517052552)
- [ ] 9. Missing stroke and margin around counter and dot - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511305455)
- [ ] 10. Jump to blur area shoud be shown behind the blur on tabs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510045776)
- [ ] 11. Wrong background color in dark mode - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510050996)
Likely it is a part of bigger issue

**Comment by cammellos** [comment]
1,2,3, 5, 6, 7, 9 seems like small fixes, 1.25 
4 I am not sure I understand fully what the issues is, could you elaborate? (maybe I am not seeing it)
8 is a bug, so we should include in 1.25

10 not sure if it's hard, I would not include it in 1.25 for now, 11 I defer to maybe @J-Son89 as he's worked on homogenizing dark mode/light mode

**Comment by churik** [comment]
added screen on 4

**Comment by flexsurfer** [comment]
- [x] 1. Date and hour are not aligned in chats list - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511309210)  
- [x] 2. Wrong margin between list items - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510226396)  
- [x] 3. The badge is not aligned with  date and hour  and name - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306952)  
- [x] [can't replicate]4. Unread barge may overlap with text and not aligned to design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511306759) 
![image](https://github.com/status-im/status-mobile/assets/4557972/2bcfe7fe-cac5-4178-8f7e-b8163b5edbd7)
- [x] 6. + uses outdated color - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510043895)  
- [x] 7. Unmute icon may overlap with date - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510042990)  
- [x] 8. When user set nickname, their real name is not shown anymore - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#517052552)



- [ ] [should be a separate issue, it's not just a border, and not only for messages home, it should be done for all places , like for shell etc] 5. Missing counter border - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510044277)  
- [ ] [same issue as 5] 9. Missing stroke and margin around counter and dot - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511305455)
- [ ] [is a separate issue related to shell - https://github.com/status-im/status-mobile/pull/17015] 10. Jump to blur area shoud be shown behind the blur on tabs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510045776)
- [ ] [is blur related, not possible to fix for now] 11. Wrong background color in dark mode - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510050996)
Likely it is a part of bigger issue

**Comment by flexsurfer** [comment]
5. Missing counter border - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510044277)
should be a separate issue, it's not just a border, and not only for messages home, it should be done for all places , like for shell etc
9 same issue as 5

**Comment by flexsurfer** [comment]
11 is blur related, not possible to fix for now

**Comment by flexsurfer** [comment]
10 is a separate issue related to shell - https://github.com/status-im/status-mobile/pull/17015
