### ISSUE TITLE
Design review: discover communities

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16861]
- [ ] 1. Wrong spacing - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510267875)  
- [ ] 2. Buttons background on `x`  [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511295255)  
- [ ] 3. Wrong margin   - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510228652)  
- [ ] 4. Wrong font size - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511274377)
- [ ] 5. Card proportion **(Android only)**- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275324)
- [ ] 6. Missing shadow on card  **(Android only)**- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275579)

**Comment by cammellos** [comment]
1,2,3,4 small issues, 1.25
5 is a bit fiddlier maybe, so would not spend too much time on it

6 looks like it could be trouble, I would not spend too much time on it for now

**Comment by mohsen-ghafouri** [comment]
> * [X] 1. Wrong spacing - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510267875)
> * [X]  2. Buttons background on `x`  [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511295255)
> * [X]  3. Wrong margin   - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510228652)
> * [X]  4. Wrong font size - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511274377) (it seems already handled)
> * [X]  5. Card proportion **(Android only)**- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275324)
> * [X]  6. Missing shadow on card  **(Android only)**- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511275579)
