### ISSUE TITLE
Design review: join community screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16862]
- [x] 1. Small font - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510722370)  
- [x] 2. Additional line inside community logo **(Android only)** - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511298876)  
- [x] 3. Top margin with opened bottom sheet - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510729314)  
- [x] 4. Wrong font size - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510728917) 
- [x] 5. Wrong font - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510728659)  
- [x] 6. The color inside the checkbox is lighter than in design - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510726719)

**Comment by cammellos** [comment]
1,3,4,5 seems like small fixes, 1.25

2 could be fiddly if some sort of bug, probably worth having a look but not spend too much time on it

6 also looks smallish, but less sure

**Comment by jo-mut** [comment]
@Francesca-G @churik 
On point 2: of this issue, its a bit unclear to me which figma would be the right to work this on this comment in the link below https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#510729314

It appears some figma designs do not really respect the top margin pointed out in the design review for join communities. Could you check the following links. Some designs have the top margin and other dont really have it
https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=1733%3A125697&mode=design&t=mxl8QDEdGZOxIC67-1

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=13521%3A714912&mode=design&t=mxl8QDEdGZOxIC67-1

1. It seems to me the maximum height for the bottom sheet showing the community rules is correctly implemented as it is now and the top margin is determined by how much the content of the bottom sheet is. More content on the bottom sheet less top margin and less content has a bigger top margin.

I seek your clarification if i may have misunderstood this. Thanks
