### ISSUE TITLE
Design review: pinned message drawer

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16875]
- [x] 1.  Title is too big - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511498551)  
- [x] 2. Margins - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511498899)  
- [x] 3. Spacing between name and message doesn't match designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511500300)
- [ ] 4.Too big icons - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511501291)

**Comment by cammellos** [comment]
All of these seems to be small issues, adding to 1.25 for now

**Comment by ibrkhalil** [comment]
@Francesca-G Please take a look at [this](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511499221) comment

**Comment by ibrkhalil** [comment]
Awaiting response from @Francesca-G
