### ISSUE TITLE
Design review: pinned message 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16876]
- [x] 1. Remove identicoin ring on user avatar - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511507832)  
- [x] 2. Small icon - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511507482)  
- [x] 3. too heavy/dark font (**Android only**)- comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511509265)  
- [x] 4. Icon is not aligned (**Android only**) - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511509855)  
- [x] 5. Pressed state doesn't have rounded corners and correct margins - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511508797)

**Comment by cammellos** [comment]
1 better to do after @yqrashawn work on identicon ring
2,3,4,5 seems small issues, I'd be inclined to add them to 1.25

**Comment by ibrkhalil** [comment]
I think we disabled pressed state from system messages like the pinned message one.

**Comment by churik** [comment]
@ibrkhalil yes, I agree - can not long-press on system message anymore from both platforms, so I consider this as resolved.
