### ISSUE TITLE
Design review: create profile password 

### ISSUE THREAD

**Issue by mohsen-ghafouri** [status-im/status-react#17503]
* [x] 1. "Tips to improve password" text alignment - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:183&mode=design#567057141)
* [x] 2. Password circle progress bar size  - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#570703335)
* [ ] 3. Password circle should animate as password improves  - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#567045823)
