### ISSUE TITLE
Finish the "Enable notifications" screen

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#17506]
# Definition of done

- [ ] 1. Update the copy on the top text container - [message](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#569642626)
- [ ] 2. Add missing icon to the "Enable notifications" button - [message](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#569642311)
- [ ] 3. Add animation (get in touch with the design team or @pedro-et) - [message](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:67315&mode=design#569642792)
