### ISSUE TITLE
feedback for toast notification in 1:1 chat

### ISSUE THREAD

**Issue by BalogunofAfrica** [status-im/status-react#17540]
# Bug Report

- [ ] Wrong color and icon for error state (https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#570468876)
- [ ] Icon is not aligned with toast text (https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#567127862)
- [ ] Wrong position of toast banner (https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:43270&mode=design#567142410)

Design review here: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#570508962

**Comment by Shritesh99** [comment]
Hi, Can I work on the issue?

**Comment by Samyoul** [comment]
If picking up this issue please ping @alwx as he has context.
