### ISSUE TITLE
Design Review: Share Screen

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17569]
- [ ] 1. Toast has wrong theme - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:66732&mode=design#570499944)
- [ ] 2. Either the button is too close to the top or the toast is in the wrong place - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:8254&mode=design#567186677). - Was not able to reproduce on iPhone 11 Pro Simulator & Pixel 7a.
- [ ] 3. Fix spacing - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:66732&mode=design#570500481)
- [ ] 4. Wrong user image in the middle of the share screen qrcode - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5960:8254&mode=design#567186888)
  - Reproducible when the user doesn't have a profile picture
