### ISSUE TITLE
Design Review: Communities

### ISSUE THREAD

**Issue by ajayesivan** [status-im/status-react#17566]
- [ ] 1. Icon in tag look too big - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5958:55521&mode=design#567061210)
- [ ] 2. All channels have a lock icon - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569667689)
- [ ] 3. if community name doesn't fit it should be on 2 lines - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569675478). This may need design input.
- [ ] 4. if there's no category for the channels we shouldn't display this "none" category at the top - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:85237&mode=design#569678148)

**Comment by Samyoul** [comment]
@clauxx I've unassigned you here just so we can focus on this issue with the Fit and Finish crew. Let us know if there is anything that you've done that you need to do.

CC @BalogunofAfrica

**Comment by clauxx** [comment]
@Samyoul @BalogunofAfrica  :+1:  I fixed [1](https://github.com/status-im/status-mobile/commit/2f22fdf1233e3273ae73df43a87c57e4de99193d) and [4](https://github.com/status-im/status-mobile/commit/901d1676f8de6a48e356e39d66cd380a51cd1168) so far. Linked the commits in case you want to use it.

**Comment by BalogunofAfrica** [comment]
> @Samyoul @BalogunofAfrica 👍 I fixed [1](https://github.com/status-im/status-mobile/commit/2f22fdf1233e3273ae73df43a87c57e4de99193d) and [4](https://github.com/status-im/status-mobile/commit/901d1676f8de6a48e356e39d66cd380a51cd1168) so far. Linked the commits in case you want to use it.

Thank you

**Comment by BalogunofAfrica** [comment]
2 is not reproducible on my end. It seems to have been covered by the refactor of the component here:

https://github.com/status-im/status-mobile/pull/17070

**Comment by ajayesivan** [comment]
@BalogunofAfrica 2 was fixed in this PR: https://github.com/status-im/status-mobile/pull/17799
