### ISSUE TITLE
improve lint and lint-fix

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#17641]
- [x] zprint conflicts with clojure-lsp when formatting `ns` https://github.com/status-im/status-mobile/pull/17496#discussion_r1358337423
- [x] lint against not requiring quo2 component from `quo2.core` (when outside of quo2) https://github.com/status-im/status-mobile/pull/17290#discussion_r1327568604 => https://github.com/status-im/status-mobile/pull/17828
- [ ] revisit https://github.com/orgs/status-im/teams/mobile-devs/discussions/1 check resolved zprint [issue 1](https://github.com/kkinnear/zprint/issues/273?notification_referrer_id=NT_kwDOAOZDlrM0NjcyOTcyNjQwOjE1MDkwNTgy#issuecomment-1716156544) 
- [x] and [issue 2](https://github.com/kkinnear/zprint/issues/271?notification_referrer_id=NT_kwDOAOZDlrM0NjcyODYyMzE5OjE1MDkwNTgy&notifications_query=repo%3Akkinnear%2Fzprint#event-10349700997), format once instead of twice in lint-fix => unfortunately, still need to format twice https://github.com/status-im/status-mobile/issues/17641#issuecomment-1794297585
- [x] lint `status-im2.core`, make sure `status-im2.setup.i18n-resources` is first one in the require list => PR at https://github.com/status-im/status-mobile/pull/17905
- [ ] follow rule of defn issue https://github.com/kkinnear/zprint/issues/282
- [ ] commented ns in `:require` got duplicated on every `lint-fix`, might have something to do with lsp sort-ns https://github.com/status-im/status-mobile/pull/18265
- [ ] keep rf/reg-xxx and the event key at the same line https://github.com/status-im/status-mobile/pull/19474#discussion_r1559641526

**Comment by yqrashawn** [comment]
with zprint-1.2.8, still need to format twice 
![CleanShot 2023-11-06 at 16 23 05](https://github.com/status-im/status-mobile/assets/15090582/0fda7b0a-7cae-4f52-a139-b553eb093a91)

change to community style format twice, revert rule back, format twice
second format looks like, seems nothing to do with comments
![CleanShot 2023-11-06 at 16 27 48](https://github.com/status-im/status-mobile/assets/15090582/ab785993-752c-4e76-adfe-fad96fad9536)
