### ISSUE TITLE
Upgrade `react-native` to `0.73.x`

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-react#18291]
### Todos:

- [x] Get `iOS` build working with `react-native` `0.73.x` locally
  - [x] Upgrade `react-native-webview` to `13.6.3` -> https://github.com/status-im/status-mobile/pull/18295
- [x] Get `iOS` build working with `react-native` `0.73.x` on CI -> https://github.com/status-im/status-mobile/pull/18255
  - [x] fix `iOS` build issue -> https://github.com/status-im/status-mobile/issues/18548
- [x] Get Android build working with `react-native` `0.73.x` locally 
  - [x] Convert `Java` code to `Kotlin` -> https://github.com/status-im/status-mobile/pull/18293
- [x] Get `Android` build working with `react-native` `0.73.x` on CI -> https://github.com/status-im/status-mobile/pull/18496
- [x] Upgrade `jest` to `29.x` -> https://github.com/status-im/status-mobile/pull/18276
- [x] Merge `Android` & `iOS` branches and resolve build issues.
- [x] Unit Tests Pass
- [x] Integration Tests Pass
- [x] Component Tests Pass
- [x] E2E Tests Pass 79% ✅ -> https://github.com/status-im/status-mobile/pull/18496#issuecomment-1895412804
