### ISSUE TITLE
[Epic] - Feature - Wallet - Save Address 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18568]
### User Story

- As a user, I want to be able to save an address (with ENS if registered) in the wallet settings so that I can quickly choose it for future transactions. 
- I want to be able to give the user a name, color and set the network preferences for what networks to send them tokens on.
- I want to be able to select this saved address when making another transaction in the future
- I want to edit the name, color and network preferences of the saved address
- I want to remove the saved address

### Designs

[Link to Figma](https://www.figma.com/design/hLFPHYnuM0pOzgiabtqQ6k/Descoped-Wallet-settings-for-Mobile?node-id=74-33979&t=QFZQHEfCuyRyrDG5-1)

#### Features
The below features should be hidden behind a feature flag.

add a dedicated screen to list saved addresses:
- [x] https://github.com/status-im/status-mobile/issues/19726

list saved addresses
- [x] https://github.com/status-im/status-mobile/issues/19727

search in the saved addresses list
- [x] https://github.com/status-im/status-mobile/issues/20442

add saved address by typing/pasting the address
- [x] https://github.com/status-im/status-mobile/issues/19764

add network configuration for saved address:
- [x] https://github.com/status-im/status-mobile/issues/16995

add saved address via ens
- [x] https://github.com/status-im/status-mobile/issues/19765

add saved address by scanning QR code
- [x] https://github.com/status-im/status-mobile/issues/19766

saved address operations 
- [x] https://github.com/status-im/status-mobile/issues/19728

share saved address as a QR code
- [x] https://github.com/status-im/status-mobile/issues/19734

edit saved address
- [x] https://github.com/status-im/status-mobile/issues/19737

delete saved address
- [x] https://github.com/status-im/status-mobile/issues/19730

load saved address on send page:
- [x] https://github.com/status-im/status-mobile/issues/16993

#### Closing this issue

Once all of these issues are ready the corresponding feature Flag Can be removed. This PR to remove the feature flag can then be used for QA and Design to ensure everything is feature complete and this issue can be closed.

**Comment by shivekkhurana** [comment]
The network preferences selector component is tied to the account

```clj
        {:keys [color address
                network-preferences-names]} (rf/sub [:wallet/current-viewing-account])
```

But I need to re-use it to save a recipient address. I'll create an issue to handle that.
