### ISSUE TITLE
[Epic] -Feature- Wallet - Remove Account 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18575]
All features related to issue for epic - https://github.com/status-im/status-mobile/labels/%3AMobile%20Wallet%20Feature%20-%20Delete%20Account

This issue should be hidden with a `feature-flag` so that it is not in the Nightly develop and only viewable/workable for those required to see the feature.

### User Story

- As a user, I want to be able to delete a wallet account.

- Depending on the account type the warning message should be different.
In particular generated accounts should warn me to appropriately back up keypair or recovery phrase and also the derivation path with an option to copy to this derivation path

- Once the wallet account is removed I want to instantly see this.

- This option should be able to be access from the account options actions and also from the edit page.

- Once an account is deleted a toast should show me that this activity has happened

- I should not be able to delete the first account I am given with my Status Profile and for this account the option to remove the account should not be visible.

- If I go to make a new wallet account, the default name for watch only address and account generation should be respective to how many wallet accounts I have visible in my Status Profile

- once I remove an account the balances should reflect the users updated balance.

### Tasks
Add UI to delete wallet account
- [x] https://github.com/status-im/status-mobile/issues/18421

Connect backend to delete wallet account, display toast and refresh accounts data
- [x] https://github.com/status-im/status-mobile/issues/18422

Hide Option to remove account for default wallet account
- [x] https://github.com/status-im/status-mobile/issues/18576

Default Account Names on creation are relative to how many wallet accounts the user has
- [x] https://github.com/status-im/status-mobile/issues/18416

### Designs 
[Figma Link](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=900%3A233949&mode=design&t=PjyYX6y911TQlcCl-1)

### Closing this issue
Once all of these issues are ready the corresponding feature Flag Can be removed. This pr to remove the feature flag can then be used for QA and Design to ensure everything is feature complete and this issue can be closed.
