### ISSUE TITLE
[EPIC] -  Add contract/ integration test coverage to RPC events used in the wallet

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18587]
Description:
As a developer in the mobile wallet I want to have ensure our uses of Status Go RPC endpoints are not broken. For this I would like coverage of all RPC endpoints for how we are using the api within the context of the mobile wallet.

### Tasks
- [x] https://github.com/status-im/status-mobile/pull/18665
- [x] https://github.com/status-im/status-mobile/issues/18782
- [x] https://github.com/status-im/status-mobile/issues/18352
- [x] https://github.com/status-im/status-mobile/issues/18351
- [x] https://github.com/status-im/status-mobile/issues/18350
- [x] https://github.com/status-im/status-mobile/issues/18349
- [x] https://github.com/status-im/status-mobile/issues/18348
- [x] https://github.com/status-im/status-mobile/issues/18347
- [x] https://github.com/status-im/status-mobile/issues/18346
- [x] https://github.com/status-im/status-mobile/issues/18345
- [x] https://github.com/status-im/status-mobile/issues/18344
- [x] https://github.com/status-im/status-mobile/issues/18342
- [x] https://github.com/status-im/status-mobile/issues/18343
- [x] https://github.com/status-im/status-mobile/issues/18341
- [x] https://github.com/status-im/status-mobile/issues/18340
- [x] https://github.com/status-im/status-mobile/issues/18614

misc 
- [x] https://github.com/status-im/status-mobile/issues/18359

Notes:
This feature should not need QA or design review. Best to sync with @cammellos once done as we can notify the Status-Go devs about putting this as part of their CI process, most likely not mandatory until proven stable. see https://github.com/status-im/status-go/issues/4518

**Comment by J-Son89** [comment]
also review this issue - https://github.com/status-im/status-mobile/issues/17921
