### ISSUE TITLE
[Epic] - Feature - (Wallet) Add bridging feature for tokens

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18588]
## User Story
- As a user, I would like to be able to bridge tokens from one network to another.
- I would like to be able to do this on prod and testnets.
- I am okay to work with just the best suggested route for the time being
- I would like to see the status of the transaction once it has been confirmed/failed
- I would like to see an estimation of how the gas fees will be and how much time it will take.
- on the transaction confirmation page I would like to know that I am bridging tokens 
- on the asset input page I would like to know that I am confirming a bridge transaction

## Designs
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=851-213807&mode=design&t=RuyhufmiW7Y5H6pU-4

## Issues
- [x] https://github.com/status-im/status-mobile/issues/18540
- [x] https://github.com/status-im/status-mobile/issues/18529

Get real data for select asset page
- [x] https://github.com/status-im/status-mobile/issues/18589

Update UI and data model (re-frame) on Select Input Page to handle Bridging flow
- [x] https://github.com/status-im/status-mobile/issues/18591

Update UI Transaction Confirmation to handle Bridging flow and connect RPC request
- [x] https://github.com/status-im/status-mobile/issues/18590

Make bridging transactions work after confirming the transaction
- [x] https://github.com/status-im/status-mobile/issues/18938

### Developer Notes:
discussed with @briansztamfater and it's best to keep the data model under the same scope as used in `:send` 👍 

Closing this issue
Once all of these issues are ready the corresponding feature Flag Can be removed. This pr to remove the feature flag can then be used for QA and Design to ensure everything is feature complete and this issue can be closed.

It is unclear from the designs whether the transaction Progress Page will change depending whether it is a bridging transaction or not, please align with design to see.
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2416-492967&mode=design&t=RuyhufmiW7Y5H6pU-4

**Comment by OmarBasem** [comment]
@J-Son89 What is the prioritization for this epic? For which release/month do we need it?

**Comment by J-Son89** [comment]
This will be for 1.28 release - so we can put this as part of work to be done in March 👌

**Comment by OmarBasem** [comment]
> This will be for 1.28 release - so we can put this as part of work to be done in March 👌

Added a flag for March, but named it Feb/March for now in case we had the capacity to start working on some 1.28 issues towards end of Feb. Feel free to adjust as you see fit 👍

**Comment by J-Son89** [comment]
@OmarBasem - best to just use two labels in that case. `E:Mobile Wallet February` &  `E:Mobile Wallet March` 👍 
but anyway I moved this to February as discussed with @briansztamfater and he wants to mostly complete bridging first before implementing the advanced routing in wallet.

**Comment by OmarBasem** [comment]
> @OmarBasem - best to just use two labels in that case. `E:Mobile Wallet February` & `E:Mobile Wallet March` 👍 but anyway I moved this to February as discussed with @briansztamfater and he wants to mostly complete bridging first before implementing the advanced routing in wallet.

Sounds good 👍

**Comment by OmarBasem** [comment]
@J-Son89 a comment on the epic title "Add bridging feature for best route", should be "Add bridging feature for tokens", right?

**Comment by J-Son89** [comment]
Yes this is just for tokens!

**Comment by briansztamfater** [comment]
Added #18938 to the list as #18590, where I intended to implement the logic to execute a bridging transaction, was larger than expected, so needed to split it in two parts
