### ISSUE TITLE
[EPIC] - Add Malli coverage to wallet design system components

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18586]
Description:
As a developer I want to have [malli](https://github.com/metosin/malli) specs written for design system components so that the component api is easier to understand and to help prevent it being broken with future updates made to it.

### Tasks

- [x] https://github.com/status-im/status-mobile/issues/18354
- [x] https://github.com/status-im/status-mobile/issues/18356
- [x] https://github.com/status-im/status-mobile/issues/18357
- [x] https://github.com/status-im/status-mobile/issues/18353

Notes:
These issues don't require QA or Design input, it is best to align with @yqrashawn, @ilmotta, @ajayesivan @clauxx to ensure the specs are up to spec :)

**Comment by J-Son89** [comment]
Closing this epic as all issues were complete 👍
