### ISSUE TITLE
[Epic] - Wallet bugs February

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18611]
A series of bugs to fix for February

These bugs are prioritised high to low, if adding any issues to this list be sure to prioritise it correctly.

If taking an issue it is better to take the higher priority issues first :)

### Issues

- [x] https://github.com/status-im/status-mobile/issues/18603
- [x] https://github.com/status-im/status-mobile/issues/18685
- [x] https://github.com/status-im/status-mobile/issues/18681
- [x] https://github.com/status-im/status-mobile/issues/18894
- [x] https://github.com/status-im/status-mobile/issues/18412
- [x] https://github.com/status-im/status-mobile/issues/18735
- [x] https://github.com/status-im/status-mobile/issues/18751
- [x] https://github.com/status-im/status-mobile/issues/18777
- [x] https://github.com/status-im/status-mobile/issues/18780
- [x] https://github.com/status-im/status-mobile/issues/18750
- [x] https://github.com/status-im/status-mobile/issues/18447
- [x] https://github.com/status-im/status-mobile/issues/18652
- [x] https://github.com/status-im/status-mobile/issues/18834
- [x] https://github.com/status-im/status-mobile/issues/18847
- [x] https://github.com/status-im/status-mobile/issues/18874
- [x] https://github.com/status-im/status-mobile/issues/18876
- [x] https://github.com/status-im/status-mobile/issues/18877
- [x] https://github.com/status-im/status-mobile/issues/18925
- [x] https://github.com/status-im/status-mobile/issues/18950
- [x] https://github.com/status-im/status-mobile/issues/18736
- [x] https://github.com/status-im/status-mobile/issues/18740
- [x] https://github.com/status-im/status-mobile/issues/18779
- [x] https://github.com/status-im/status-mobile/issues/18613
