### ISSUE TITLE
[EPIC] - Wallet Refactors February

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18612]
A series of refactors

### Issues
In order of priority -
- [x] https://github.com/status-im/status-mobile/issues/18559
- [x] https://github.com/status-im/status-mobile/issues/18608
- [x] #18701
- [x] https://github.com/status-im/status-mobile/issues/18067
- [x] https://github.com/status-im/status-mobile/issues/18724
- [x] https://github.com/status-im/status-mobile/issues/18700
- [x] https://github.com/status-im/status-mobile/issues/18264
- [x] https://github.com/status-im/status-mobile/issues/18566
- [x] https://github.com/status-im/status-mobile/issues/18595
- [x] https://github.com/status-im/status-mobile/issues/18358
- [x] https://github.com/status-im/status-mobile/issues/17578
- [ ] #18703 (again, more general than just wallet) - maybe discuss in April
let's check this
- [ ] https://github.com/status-im/status-mobile/issues/18702 (related but probably more general than just wallet)

##
