### ISSUE TITLE
[Epic] Wallet: Send flow - Networks and Routes

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18673]
This is a master issue to cover all issues related to routes and networks in the send flow.

### Features

- When a user selects a token and enters a value, the app should show the best route(s). 
- The user should be able to edit the receiver networks
- The user should be able to disable some networks as the source
- The user should be able to specify certain amount to be sent from a specific network
- The user should be able to long press on a given network to specify the exact amount they would like to send via that network

[Designs.](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7701-157501&mode=design&t=ixZfAk9WMF6w4KRx-4)

### Issues

- [x] https://github.com/status-im/status-mobile/issues/18248
- [x]  https://github.com/status-im/status-mobile/issues/18387
- [x] https://github.com/status-im/status-mobile/issues/18278
- [x] https://github.com/status-im/status-mobile/issues/18582
- [x] https://github.com/status-im/status-mobile/issues/18655
- [x] https://github.com/status-im/status-mobile/issues/16974
- [x] https://github.com/status-im/status-mobile/issues/19670
- [x] https://github.com/status-im/status-mobile/issues/19791
- [x] https://github.com/status-im/status-mobile/issues/19910

**Comment by J-Son89** [comment]
closing as it's done :)
