### ISSUE TITLE
[Epic] - Feature - (Wallet) Add support for multiple collectibles

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18697]
## User Story

- As a user, I would like to be able to hold collectibles that I own multiple times  (multiple nfts)
- I would like to be able to view these collectibles and be aware it's a multiple nft that I am viewing
- I would like to be able to send multiple collectibles in the same transaction. To any quantity,
- I would like to know when the collectible I am trying to render is an unsupported file or that the data cant be fetched properly.

Note: we will not handle the full UI for  transaction progress page in this epic - just the basic information
<img width="209" alt="Screenshot 2024-03-08 at 11 00 59" src="https://github.com/status-im/status-mobile/assets/22799766/a330ac7d-38bc-45bf-bd19-2f8e929a8cc4">

## Designs

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7247-86242&mode=design&t=n4wHg9GsEAOhFSRw-4

## Issues

Add Collectible Counter component
- [x] https://github.com/status-im/status-mobile/issues/18632
Add Collectibles List Item
- [x] https://github.com/status-im/status-mobile/issues/19086
Add Expanded Collectible Component
- [x] https://github.com/status-im/status-mobile/issues/19286
Add support in Wallet UI for  multiple NFT's
- [x]  https://github.com/status-im/status-mobile/issues/19140
Add ui for sending multiple collectibles
- [x] https://github.com/status-im/status-mobile/issues/19141
Add support in Transaction Confirmation Page for multiple NFT's
- [x] https://github.com/status-im/status-mobile/issues/19142
Add backend support for sending multiple collectibles
- [x] https://github.com/status-im/status-mobile/issues/19143 

### Developer Notes:
Please align with Desktop & Design when working on this feature epic

Closing this issue
Once all of these issues are ready the corresponding feature Flag Can be removed. This pr to remove the feature flag can then be used for QA and Design to ensure everything is feature complete and this issue can be closed.
