### ISSUE TITLE
[EPIC] - [Feature] - Wallet - Import Private Key

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18815]
## User Story

- As a user, when generating my wallet account I would like to be able to import a private key.
- I would like to have validation on when entering the private key to ensure it is the correct format.
- I would like to know whether the account has activity or not.
- I would like to be able to add a Key Pair Name
- I would then like to be able to add that account with the private key as the origin

## Designs
https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2070-595431&mode=design&t=d987JsFas3Z5NQ67-4

## Issues

Add UI for Import private key screen
- [x] https://github.com/status-im/status-mobile/issues/18816

Add UI for Key Pair Name
- [x] https://github.com/status-im/status-mobile/issues/18817

Integrate backend for Import Private Key Screen
- [x] https://github.com/status-im/status-mobile/issues/19759

Update UI for Create Account Page to handle Private Key and allow generating depending on imported private key
- [x] https://github.com/status-im/status-mobile/issues/18818

Add validation and activity check to Import Private Key Screen
- [x] https://github.com/status-im/status-mobile/issues/18819

Add ability to remove account added with private key.
- [ ] create issue

### Developer Notes:

Some of these parts are still in design and we are awaiting finalisation.
Please align with Desktop & Design when working on this feature epic

Closing this issue
Once all of these issues are ready the corresponding feature Flag Can be removed. This pr to remove the feature flag can then be used for QA and Design to ensure everything is feature complete and this issue can be closed.
