### ISSUE TITLE
[Epic] - Wallet bugs March

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#19090]
A series of bugs to fix for March

These bugs are prioritised high to low, if adding any issues to this list be sure to prioritise it correctly.

If taking an issue it is better to take the higher priority issues first :)

Issues
- [x] https://github.com/status-im/status-mobile/issues/19099
- [x] https://github.com/status-im/status-mobile/issues/19050
- [x] https://github.com/status-im/status-mobile/issues/19158
- [x]  https://github.com/status-im/status-mobile/issues/18833
- [x] https://github.com/status-im/status-mobile/issues/19401
- [x] https://github.com/status-im/status-mobile/issues/19232
- [x] https://github.com/status-im/status-mobile/issues/18838
- [x] https://github.com/status-im/status-mobile/issues/18841
- [x] https://github.com/status-im/status-mobile/issues/18737
- [x] https://github.com/status-im/status-mobile/issues/18856
- [x] https://github.com/status-im/status-mobile/issues/19310
- [x] https://github.com/status-im/status-mobile/issues/19135
- [x] https://github.com/status-im/status-mobile/issues/19145
- [x] https://github.com/status-im/status-mobile/issues/19157
- [x] https://github.com/status-im/status-mobile/issues/19225
- [x] https://github.com/status-im/status-mobile/issues/18972
- [x] https://github.com/status-im/status-mobile/issues/19382
- [x] https://github.com/status-im/status-mobile/issues/18779
- [x] https://github.com/status-im/status-mobile/issues/18739
- [x] https://github.com/status-im/status-mobile/issues/18721
- [x] https://github.com/status-im/status-mobile/issues/18720

**Comment by J-Son89** [comment]
@status-im/mobile-qa - we can use this issue for bugs related to wallet for March.
I have copied over any of the bugs that had not been started in the last epic.
