### ISSUE TITLE
Communities - Community page issues when scrolling

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19204]
# Design Feedback 2.27

## [Communities] Issues when scrolling a community page screen
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=4%3A111403&mode=design&t=IwKFMlZGTBic5nwK-1)

- [x] - **Status bar isn't visible** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35475&mode=design#725950910)] might be related to this issue logged here: status-im/status-mobile/issues/15260

- [ ] - **Channel top bar blur** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#727200564)] isn't behaving correctly causing the community header image to not be visible

- [x] - **Top bar gets cut off** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35475&mode=design#725946599)] when scrolling (see the narrow margin between ❌ button and top nav bottom)

- [ ] - **Divider label margin** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35475&mode=design#725948018)] of channel categories doesn't match design

<img width="500" alt="Screenshot 2024-03-12 alle 14 56 08" src="https://github.com/status-im/status-mobile/assets/122543089/37cb73f1-d201-429a-a878-d42d2fe9b2a8">

### Reproduction

1. Open a community
2. Scroll channel list

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Issue 1 no longer reproducible
Issue 2 will be fixed in https://github.com/status-im/status-mobile/pull/19665
working on Issue 3 and Issue 4

**Comment by Parveshdhull** [comment]
Issue 3 is also fixed, top bar is not cutting anymore
![image](https://github.com/status-im/status-mobile/assets/17097240/78db4929-528f-4df9-b2ad-3f44e0f90fbd)
