### ISSUE TITLE
[Epic] - Wallet bugs April

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#19466]
A series of bugs to fix for April

These bugs are prioritised high to low, if adding any issues to this list be sure to prioritise it correctly.

If taking an issue it is better to take the higher priority issues first :)

Issues
- [x] https://github.com/status-im/status-mobile/issues/19595
- [x] https://github.com/status-im/status-mobile/issues/19752
- [x] https://github.com/status-im/status-mobile/issues/19743
- [ ] https://github.com/status-im/status-mobile/issues/19533
- [x] https://github.com/status-im/status-mobile/issues/19611
- [x] https://github.com/status-im/status-mobile/issues/19596
- [x] https://github.com/status-im/status-mobile/issues/19431
- [x] https://github.com/status-im/status-mobile/issues/19473
- [x] https://github.com/status-im/status-mobile/issues/19703
- [x] https://github.com/status-im/status-mobile/issues/19372
- [x] https://github.com/status-im/status-mobile/issues/18875
- [x] https://github.com/status-im/status-mobile/issues/19818
- [x] https://github.com/status-im/status-mobile/issues/19817
- [x] https://github.com/status-im/status-mobile/issues/19344
- [x] https://github.com/status-im/status-mobile/issues/19610
- [x] https://github.com/status-im/status-mobile/issues/19496
- [x] https://github.com/status-im/status-mobile/issues/19544
- [x] https://github.com/status-im/status-mobile/issues/19646
- [x] https://github.com/status-im/status-mobile/issues/19221
- [x] https://github.com/status-im/status-mobile/issues/19599
- [x] https://github.com/status-im/status-mobile/issues/19156
- [x] https://github.com/status-im/status-mobile/issues/19741
- [x] https://github.com/status-im/status-mobile/issues/19444
- [x] https://github.com/status-im/status-mobile/issues/18951
- [x] https://github.com/status-im/status-mobile/issues/19472
- [x] https://github.com/status-im/status-mobile/issues/19769
- [x] https://github.com/status-im/status-mobile/issues/19442
- [x] https://github.com/status-im/status-mobile/issues/19519
- [x] https://github.com/status-im/status-mobile/issues/19440
- [x] https://github.com/status-im/status-mobile/issues/19463
- [x] https://github.com/status-im/status-mobile/issues/18657
- [x] https://github.com/status-im/status-mobile/issues/19375
- [x] https://github.com/status-im/status-mobile/issues/19788
- [x] https://github.com/status-im/status-mobile/issues/18631
- [x] https://github.com/status-im/status-mobile/issues/19542
- [x] https://github.com/status-im/status-mobile/issues/19534
- [x] https://github.com/status-im/status-mobile/issues/18695
- [x] https://github.com/status-im/status-mobile/issues/19745
- [x] https://github.com/status-im/status-mobile/issues/19697
- [x] https://github.com/status-im/status-mobile/issues/19607
- [x] https://github.com/status-im/status-mobile/issues/18527
- [x] https://github.com/status-im/status-mobile/issues/19540
- [x] https://github.com/status-im/status-mobile/issues/19739
- [x] https://github.com/status-im/status-mobile/issues/19746
- [x] https://github.com/status-im/status-mobile/issues/19543
- [x] https://github.com/status-im/status-mobile/issues/19774
- [x] https://github.com/status-im/status-mobile/issues/19775
- [x] https://github.com/status-im/status-mobile/issues/19776
- [x] https://github.com/status-im/status-mobile/issues/19777
- [x] https://github.com/status-im/status-mobile/issues/19778
- [x] https://github.com/status-im/status-mobile/issues/19779
- [x] https://github.com/status-im/status-mobile/issues/19545
- [x] https://github.com/status-im/status-mobile/issues/19757
- [x] https://github.com/status-im/status-mobile/issues/19650
- [x] https://github.com/status-im/status-mobile/issues/19657
- [x] https://github.com/status-im/status-mobile/issues/19809
- [x] https://github.com/status-im/status-mobile/issues/19658

**Comment by J-Son89** [comment]
@status-im/mobile-qa - I copied over any unassigned bugs from March epic https://github.com/status-im/status-mobile/issues/19090 to here. 

Let's use this issue for April 👌

**Comment by J-Son89** [comment]
closing this epic as we have moved to the solution of using labels for wallet bugs 👍 

All of these issues are still very relevant :)
