### ISSUE TITLE
[EPIC] Wallet Activity

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#19849]
Umbrella issue for the activity items in wallet.

- [x] https://github.com/status-im/status-mobile/issues/19825
- [x] https://github.com/status-im/status-mobile/issues/19850
- [x] https://github.com/status-im/status-mobile/issues/19851
- [x] https://github.com/status-im/status-mobile/issues/19852
- [x] https://github.com/status-im/status-mobile/issues/19956
- [x] https://github.com/status-im/status-mobile/issues/19981
[Designs](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1070-284225&mode=design&t=05G37UXdKebXGVOI-4)

**Comment by shivekkhurana** [comment]
This epic needs to be reworked to reflect the idea of local activity.

**Comment by churik** [comment]
I think  we can close this one, @shivekkhurana reopen if it still makes sense to keep it open
