### ISSUE TITLE
[EPIC] Mobile Swap M1

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-react#19900]
Desktop equivalent: https://github.com/status-im/status-desktop/issues/14598

### Description

Initial implementation of Swap operations in the Wallet. Basic UI, using Paraswap as our aggregator.

Figma: https://www.figma.com/design/AD2JSKg0I8dZcylyiGa62O/Swap-for-Mobile?node-id=48-156836&t=7KpdOMFQflEZx0MM-0

User Stories: https://www.notion.so/Mobile-Swaps-V1-986bfa221de449508664c282f1f90662

## General
- [x] Iterate on designs for Approve+Swap process
- [x] Write User Stories

## UI Components
- [x] #19996
- [x] #19997

## Mobile Client
- [x] https://github.com/status-im/status-mobile/issues/19919
- [x] https://github.com/status-im/status-mobile/pull/20029
- [x] #20246

**Comment by alwx** [comment]
All the subissues are closed, should this one be closed as well?

**Comment by briansztamfater** [comment]
Agree, we can close this

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmpmZjJ3cjR6Y3AwejR0Y2U4NGR3N20zY2YyNW11Y3k2N2puNWluaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JJfkt7QEKRvMY6JwDL/giphy-downsized.gif)
