### ISSUE TITLE
Discover pixel perfect: Main screen

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2076]
### User Story

As a user, I want discover screens to look pretty like in the design so that using discover is a delight.

### Description

*Type*: Bug

*Summary*: There are a number of discrepancies between the design and Discover. The goal of this issue is to capture the main ones for: Main Screen.

#### Expected behavior
![image](https://user-images.githubusercontent.com/1552237/31393637-8060e1e2-addc-11e7-9782-d6b1652c4a16.png)
![image](https://user-images.githubusercontent.com/1552237/31393648-8534646e-addc-11e7-879a-22109155acdc.png)

#### Actual behavior
iOS only for now - Android screens to come.

![image](https://user-images.githubusercontent.com/1552237/31548194-52bce600-b02a-11e7-8dd4-960279120516.png)
![image](https://user-images.githubusercontent.com/1552237/31548198-56f9b8c4-b02a-11e7-8fed-8c0cf749c09e.png)

Android (Oct 16)
![image](https://user-images.githubusercontent.com/1552237/31607758-e1c8edae-b26d-11e7-8c30-1286e09f4445.png)
![image](https://user-images.githubusercontent.com/1552237/31607772-ed80bd8e-b26d-11e7-865a-72932a99c361.png)

#### List of things to fix (non-exhaustive)
- [x] Recent statuses etc headers font lowercase
- [x] Status font margin to below
- [x] Name Icon not centered for cards
- [x] Popular hashtag grey margins bottom
- [x] DApps icon size - make bigger and remove `...`
- [x] DApps tighter horizontal margin (requires https://github.com/status-im/status-react/issues/2116)
- [x] DApps get rid of scrollbar
- [x] DApps grey margin to public chats
- [x] Public chats padding left

### Must have

- [ ] TEST -> Chat button either missing or wrong color&corners (Android saw on Goran's screen - will be fixed in https://github.com/status-im/status-react/issues/2119)
- [ ] TEST -> Public chats scroll to end last one covered by menu bar (hm, can't reproduce? - @annadanchenko?)
- [ ] Right font size for contact username is 14
- [ ] tap on the number of popular hashtags  -> popup ...
- [x] Popular hashtags - card has borders (at least in ios) should have no borders (lines)
- [x] All for DApps should be blue, now grey

### Nice have
- [ ] Chat button should have margin 12 px from the bottom of the card
- [ ] Too wide top margin toolbar (16 vs 8 I think)
- [ ] Size of cards should be equal (3 lines can fit) on Recent statuses
- [ ] Public chats - change title of 3 chats  to #status #testing #163 
- [ ] Popular hashtags font weight
- [ ] DApps and Public chats bg header bg color ( @denis-sharypin playing around with alt designs so hold)
- [ ] Recent statuses horizontal line header
- [ ] TEST -> check UI checklist

### MISC
@oskarth - [ ] IGNORE Android - Dapps preview not shown (?)

**Comment by oskarth** [comment]
Closed in favor of must haves https://github.com/status-im/status-react/issues/2221 and nice to haves https://github.com/status-im/status-react/issues/2222
