### ISSUE TITLE
Onboarding - Active icon color inside password field is incorrect 

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21206]
# Design Feedback

## [Onboarding] Log in screen issues

- **Eye icon colour** [[2](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#936082657)] should be white. Affects only Android.

#### Expected behavior

<img width="175" alt="Screenshot 2024-09-06 alle 15 44 25" src="https://github.com/user-attachments/assets/d665a710-d79d-46c2-81c3-9c49d83c5c50">

#### Actual behavior

<img src="https://github.com/user-attachments/assets/77b1d3b1-94c8-4d77-8ddc-eeaed65b2f4b" width="500" />

### Reproduction

1. Reach the profile creation > password input screen 

### Additional Information

- Operating System: Android 15
- Devices in the screenshots: POCO F6 Pro

**Comment by ilmotta** [comment]
@mariia-skrypnyk have you seen this issue lately? I can't reproduce it. If you confirm you can't as well we can close this issue as resolved. Thanks in advance

**Comment by mariia-skrypnyk** [comment]
- [x] Placeholder text alignment [[1](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#934557877)] inside the input field isn't centered
- [ ] Eye icon colour [[2](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#936082657)] should be white
- [x] Password dots [[3](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#937816796)] are jumping while typing, misaligned

@ilmotta @Francesca-G hi guys!

I've checked and only #2 exist in latest develop (Android).
At least my eyes thinks so ☺️.

**Comment by ilmotta** [comment]
Thanks for double-checking @mariia-skrypnyk. I updated the issue to reflect the current state.
