### ISSUE TITLE
[EPIC] Keycard

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#21579]
Priority 1

- [x]  https://github.com/status-im/status-mobile/issues/21575
- [x] https://github.com/status-im/status-mobile/issues/21618
- [x]  https://github.com/status-im/status-mobile/issues/21573
- [x]  https://github.com/status-im/status-mobile/issues/21559
- [x]  https://github.com/status-im/status-mobile/issues/21619

Priority 2

- [x]  #21577

Priority 4
- [x] https://github.com/status-im/status-mobile/issues/21930 
- [x]  https://github.com/status-im/status-mobile/issues/21578 
- [x] #21932

Priority 5
- [x]  #21951 
- [x] #21993

**Comment by ilmotta** [comment]
@flexsurfer @Parveshdhull I see as beneficial that we close epic issues at one point or another, even if there are still leftovers, which usually is the case with larger epics such as this one.

The goal of the epic I think is to simply track progress of multiple features, but because in 2.34 we are going to significantly slow down Keycard development and I just checked the last checkbox item in the epic description for https://github.com/status-im/status-mobile/issues/21575, I think it's fine to close this epic as resolved.

I think we can celebrate closing this epic, because it means incredible progress was made! Thank you guys 💟 

------

Ideally I'd say our epics should have a TTL or be associated with release numbers so that we limit them in scope. This helps us all make the best of epic issues and keep them in check to be closed based on clearer criteria.

Because we are quite consistent with labeling, this URL https://github.com/status-im/status-mobile/issues?q=state%3Aopen%20label%3Akeycard%20label%3Amobile-core gives a better and up-to-date view of all keycard issues.



cc @churik
