### ISSUE TITLE
Discover: must haves for 0.9.12 (pixel perfection)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2221]
All the must haves we want to solve for 0.9.12. Umbrella issue: https://github.com/status-im/status-react/issues/1874

### Main screen

- [x] TEST -> Chat button either missing or wrong color&corners (Android saw on Goran's screen - will be fixed in #2119)
- [x] TEST -> Public chats scroll to end last one covered by menu bar (hm, can't reproduce? - @annadanchenko?)
- [x] Right font size for contact username is 14
- [x] tap on the number of popular hashtags -> popup ...
- [x] Popular hashtags - card has borders (at least in ios) should have no borders (lines)
- [x] All for DApps should be blue, now grey
- [x] Disable All links for Poular hashtags and Recent statuses for empty Discover screen

### Main screen (empty state)

- [x] Too wide top margin toolbar ( for iOS it should be 76, for android 80, check other tabs in our app please) (Oskar done in checkout, PR coming Oct 17)
- [x] Goran If can fix in 1 hr do it otherwise move to nice to have - All content hidden behind right edge on smaller screen (check 5s)
- [x] "all" links should be disabled when screens are empty, https://github.com/status-im/status-react/issues/2205

### Styles Recent statuses
- [x]  margins from the screen edges should be 16 px (from the chat button to the right edge, 16 px from the left side to an userpick and status)
- [x]  top status' text has a wrong margin from the top of the card. It should be 16px
- [x]  the margin between chat button and the bottom of the status' card should 12px
- [x]  separation lines between statuses should go from the edge to the edge. Check design in zepplin
- [x] https://github.com/status-im/status-react/issues/2223 No statuses or hashtags under any network except Ropsten / Ropsten with upstream RPC

### Popular hashtags screen
- [x] Wrong title text  and non-i18n too
- [x] Toolbar missing margin, center title
- [x] Grey bg
- [x] Left align tag cloud
- [x] Tag box style
- [x] Scrollable tag list
- [x] Name icon center #2119 
- [x] Chat icon style #2119 

### DApp profile screen
- [x] open button - make it smaller — 64px for iOS, 72px for Android
- [x] Description and URL - 16px between text and the bottom edge 
- [x] add a title to the screen? like `DApp Profile`

**Comment by oskarth** [comment]
Fixed in develop, will be in 0.9.12 release
