### ISSUE TITLE
Discover: nice to haves (pixel perfect, etc)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2222]
All the nice to haves we don't need to solve for 0.9.12 but want to tackle sometime in the future. Laundry list. Umbrella issue: #1874 

### Styles Main screen
- [ ] Chat button should have margin 12 px from the bottom of the card
- [ ] Too wide top margin toolbar (16 vs 8 I think)
- [ ] Size of cards should be equal (3 lines can fit) on Recent statuses
- [ ] Public chats - change title of 3 chats to #status #testing #163
- [ ] Popular hashtags font weight
- [ ] DApps and Public chats bg header bg color ( @denis-sharypin playing around with alt designs so hold)
- [ ] Recent statuses horizontal line header

### Styles Main screen - empty states
- [ ] Font weight "Recent statuses" etc bolder
- [x] Titles for sections should be without letter spacing
- [ ] "No statuses text" should be grey ( color-gray4 [#939BA1] )
- [ ] Reduce size between title Dapps and dapps icons. it should be 24px
- [ ] Names os public chats are too bold, they need medium font weight
- [ ] Let's add a stroke to dapps icons. It will be much better with it. Use color: color-gray-transparent-light
- [ ] improve the central alignment of empty state. Move icon a bit up
- [ ] check dapp name font size. In the mocks it's 14. and they should have regular font weight

### Styles Recent statuses
- [ ] Name icon not centered
- [ ] Grey background missing
- [ ] Toolbar lack of margin, not centered
- [ ] TEST Chat button missing / style
- [ ] https://github.com/status-im/status-react/issues/2004

### Styles Popular hashtags
- [ ] Wrong title text and non-i18n too
- [ ] Toolbar missing margin, center title
- [ ] Grey bg
- [ ] Left align tag cloud
- [ ] Tag box style
- [ ] Scrollable tag list
- [ ] Name icon center #2119
- [ ] Chat icon style #2119
- [ ] margins from the screen edges should be 16 px (from the chat button to the right edge, 16 px from the left side to an userpick and status)
- [ ] improve alignment of hashtags in the top scroll view (checked on ios, they are not in the center of cell)
- [ ] top status (under hashtags) text has a wrong margin from the top of the card. It should be 16px
- [ ] separation lines between statuses should go from the edge to the edge. Check design in zepplin
- [ ] the margin between chat button and the bottom of the status' card should 12px

### Styles Search by hashtag

- [ ] iOS toolbar title wrong
- [ ] Grey bg
- [ ] Icon name thing
- [ ] Chat button missing

### Styles Dapps list
- [x] Icon size bigger
- [ ] Margin grey a tad too high
- [ ] Check small resolution (smallest iPhone) if rows should be two instead of three
- [ ] iphone 5s - to close to the edges (icons are too close) It should be 16 px between dapp icon and the edge of the screen, we could reduce distance between dapps on smaller screens . Reflected in https://github.com/status-im/status-react/issues/2210

### Styles Dapps profile
- [ ] iOS toolbar title wrong
- [ ] Grey bg
- [ ] Wrong icon bg
- [ ] Description bg
- [ ] Open icon should also be tappable, not just text
- [ ] Dapp icon is now too small, should be 56
- [ ] Wrong font color in Open text on android

### Styles Status widget
- [ ] Chat button style is wrong
- [ ] Specifically colors are wrong (purple)
- [x] Author icon is not centered with respect to his name (ios)

### Misc
- [ ] #1996 Navigate to profile from status
- [ ] #1997 Render shortened version of too long status
- [ ] #2125 Dapp selection
### Add margin and align Dapps rows to the left

**Comment by yenda** [comment]
![253554100](https://user-images.githubusercontent.com/1181225/31823563-c0c5db66-b5ac-11e7-950f-1efa8854688e.png)

There is a lack of margin on this screen:
![screenshot_1508506467](https://user-images.githubusercontent.com/1181225/31823570-c361865e-b5ac-11e7-855c-7b08757e4d6b.png)

**Comment by annadanchenko** [comment]
Discover feature is removed
