### ISSUE TITLE
ERC20 token support 

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#2464]
### User Story

As a user I want my [ERC20](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md) tokens to be first class citizen.

### Description

*Type*: Feature

*Summary*: 

A user should be able to manage its ERC20 tokens pretty much the same way as ETH.
In particular `wallet` and `send` command must support ERC20 tokens.

As a first step considered ERC20 tokens will be based on a static list embedded in the application.

See more info here: https://github.com/status-im/ideas/issues/3

## Iteration 1 checklist: 

- [ ] #2465 My asset screen layout
- [ ] #2517 My token tab UI - with non-functional buttons
- [ ] #2516 My asset screen title toolbar UI (with token logo)
- [ ] #2518 My token transactions UI
- [ ] #2466 Market value - stats data UI only - no graph
- [ ] My token - balance info 
- [ ] My token - balance info in USD from cryptocompare
- [ ] My token - transaction list data from etherscan 
- [ ] Market value data bindings - triage what info is available via APIs and implement only that

## Pushed to subsequent iterations

- Working Send and Request buttons
- SVG history graph
- Market value data points skipped from Iteration 1

**Comment by jeluard** [comment]
Removed from current scope.
