### ISSUE TITLE
[WIP] Mixpanel tracking issues.

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#3732]
WIP.  Adding notes here while testing.

- [x] Missing events for signing Dapp transaction. There should be distinct events for signing a wallet transaction or signing a dapp transaction
- [x] Event doesn't fire for tapping "+" on home
- [x] Event doesn't fire when tapping "invite friends" from "+/new" menu
- [ ] Add property to `send-current-message` with chat type (eg p2p, group, public)
- [x] `Granted push notifications` and `Denied push notifications` should be properties of `tap` like all the other tap events
- [ ] `home` event is not fired when going back from "New" screen. To reproduce: Open app and click "+" button. Then go back. The `home` event should be sent since you are on "Home" screen now
