### ISSUE TITLE
[EPIC] Port Wallet to Desktop

### ISSUE THREAD

**Issue by goranjovic** [status-im/status-react#6297]
### User Story

As a user I want Wallet on Desktop, because... Wallet on Desktop.

### Description

As the very first version, we'll just try to port the mobile Wallet directly as it is to desktop and only solve the most severe responsiveness issues. This is merely an experiment to see if it would work at all.

- [ ] port 2 panel designs to desktop
- [ ] Implement chat commands on desktop #6945
- [ ] transaction history (http calls don't work on desktop, at least not on linux) - status-im/react-native-desktop#373
- [ ] set recipient by scanning qr (camera on desktop not supported)
- [ ] offline detection - always says it's offline on linux, so it's being ignored by wallet when on desktop

<img width="1024" alt="base" src="https://user-images.githubusercontent.com/6559881/49082210-7ee0db80-f249-11e8-9603-188070922e74.png">

**Comment by EugeOrtiz** [comment]
A couple of questions to clarify this issue @goranjovic @chadyj :
- Do we want the entire the wallet functionality on desktop (send/receive)? Why? What use cases we want to cover?
- Also, if the idea is to experiment, should this be available on a different "demo" or the actual product?

**Comment by chadyj** [comment]
> * Do we want the entire the wallet functionality on desktop (send/receive)? Why? What use cases we want to cover?

Yes! 
Same use cases as mobile.

> * Also, if the idea is to experiment, should this be available on a different "demo" or the actual product?

Not an experiment. We are aiming for Status to have parity across platforms.

**Comment by denis-sharypin** [comment]
Design explorations are happening here
https://www.figma.com/file/FOmTCMdDi31GGEGr1IKUhqd3/Desktop-Wallet?node-id=0%3A1

<blockquote><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/FOmTCMdDi31GGEGr1IKUhqd3/Desktop-Wallet?node-id=0%3A1">Figma</a></strong></div></blockquote>

**Comment by churik** [comment]
Can be closed because of https://github.com/status-im/status-react/pull/7551
