### ISSUE TITLE
[Epic] Fix Message Reliability

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6757]
* Project GitHub tag: https://github.com/status-im/status-react/labels/chat-reliability

### Project Vision

The goal of this project is:
* to make messaging extremely reliable;
* to be able to prove that;
* to be able to show that information to a user (especially it is important to
    communicate if the message isn't delivered).

### Project Scope

"Message reliability" in this project means:
- being able to deliver a user's message;
- or being able to communicate to the user that her message wasn't delivered;
- with the current network topology and level of decentralization.

The scope includes research & investigation, creating toolkit to monitor and test reliability.

### Project Tradeoffs
1. ????

---

See also: 
* https://discuss.status.im/t/diagnosing-chat-reliability-issues/729
* Geth Discussion about Whisper ACKs: https://github.com/ethereum/go-ethereum/issues/18159

### Why is messaging unreliable?

- [ ] Message history differs between desktop and mobile for the same user being online at the same
    - [x] https://github.com/status-im/status-react/issues/7097

#### Mailserver requests looks like take long.
- [ ] (golang) https://github.com/status-im/status-go/issues/1279
- [ ] Deploy the changes

#### History of a particular mailserver might be lost if we upgrading it/installing it
- [x] (in progress, golang) https://github.com/status-im/status-go/issues/1290
- [x] deploy the changes

#### If a mailserver is down, it takes a long time to figure this out and switch to another one.
- [x] (in progress) https://github.com/status-im/status-go/issues/1285 (mailserver management on status-go side)

#### If a topic is crowded (like we witnessed in Prague) the response from the mailserver can quickly consume the data plan from the user. We need to think about ways to mitigate this (maybe request a preview from the mailserver so we can inform the user that messages won't be downloaded automatically for the selected chat if he's on 4G?)
- [ ] (clojure) https://github.com/status-im/status-react/issues/6758
- [ ] Whisper rate limiting
    - [x] https://github.com/status-im/status-go/pull/1222
    - [ ] (devops) enable whisper rate limiting on mailservers
    - [ ] (clojure) show traffic usage by public channels/whisper topics

#### We don't have any on-call procedures for when mailservers go down, etc. It is important with the current infrastructure, while we have our cluster.
- [x] Implement a playbook and response procedures for mailserver issues

#### Missing messages for public chats due to Whisper TTL
- [x] (in progress, clojure) https://github.com/status-im/status-react/issues/6814

#### Messaging fails on public wifi 
- [ ] (golang) #6351

--- 

DONE

#### ~Push notifications being received way before messages are downloaded, leading to "phantom" push~
- [x] Messages are marked as "sent" erroneously: https://github.com/status-im/status-go/issues/1276
    - [x] ACKs for Whisper: https://github.com/status-im/status-go/issues/1278
    - [x] (in progress, clojure) upgrade status-go && send info about the connected mailserver to status-go https://github.com/status-im/status-react/issues/6889

#### ~We don't have any way to check if the message history is consistent on the server side.~
- [x] https://github.com/status-im/statusd-bots/issues/6
- [x] deploy x-check-mailserver: https://github.com/status-im/infra-eth-cluster/issues/20

**Comment by dshulyak** [comment]
> Messages are marked as "sent" erroneously: status-im/status-go#1276

that also includes "phantom" notifications, without receiving an actual message. just in case someone looks for common issues

**Comment by mandrigin** [comment]
Yeah, I tried to put it just under this reason part, but probably it isn't the most readable way... I'll think about better formatting

**Comment by chadyj** [comment]
Another one to consider: Messaging fails on public wifi
https://github.com/status-im/status-react/issues/6351

**Comment by mandrigin** [comment]
@chadyj yeah, good point, forgot about it

**Comment by adambabik** [comment]
A tool to verify mail servers: https://github.com/status-im/statusd-bots/pull/7

**Comment by mandrigin** [comment]
@adambabik what is the task to sync mailservers (whisper opcode)?

**Comment by adambabik** [comment]
@mandrigin I think it's https://github.com/status-im/status-go/issues/1290. I don't remember creating any other issues.

**Comment by mandrigin** [comment]
@adambabik thanks! that is what I need!

**Comment by oskarth** [comment]
I'd like to propose that we include the use of https://discuss.status.im/t/introducing-a-data-sync-layer/864 in the scope of this. Happy to talk more about it.

<blockquote><img src="https://discuss.status.im/uploads/default/optimized/1X/1eb8af473d7e0391dadd4a21c7a99d807e5341a3_1_500x500.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/introducing-a-data-sync-layer/864">Introducing a data sync layer</a></strong></div><div>Introduction We want Status to be decentralized and censorship-resistant. Thus we must design our systems to work in offline environments, as well as for mesh settings.  Right now messaging is relying on 3rd party services like mail servers. They fulfill a role, relaying messages between nodes that aren’t online at the same time, but it is fragile. The system should work without it.  Data sync layer By introducing a data sync layer in our protocol, we can improve on this. It decouples message sy...</div></blockquote>

**Comment by mandrigin** [comment]
@oskarth I think we can add it to our backlog (see https://docs.google.com/document/d/18ph6ptFPzRkWQo3Dbs8xcjwG5MW3Dn6ihftiBm1W1g4/edit#)

<blockquote><div><strong><a href="https://docs.google.com/document/d/18ph6ptFPzRkWQo3Dbs8xcjwG5MW3Dn6ihftiBm1W1g4/edit#">Google Docs - create and edit documents online, for free.</a></strong></div><div>Create a new document and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Docs to edit Word files. Free from Google.</div></blockquote>

**Comment by oskarth** [comment]
Is the fact that #status-core-chat is unusable (at least for me on desktop) due to spam considered somewhat in scope? Would be useful to understand interface with chat team, since this isn't only captured in eg. TTT, and it breaks basic UX.

**Comment by mandrigin** [comment]
@oskarth it isn't unusable in Mobile, it looks like it is a desktop-specific issue

**Comment by mandrigin** [comment]
replaced by https://www.pivotaltracker.com/epic/show/4178343

<blockquote><div><strong><a href="https://www.pivotaltracker.com/epic/show/4178343">Reliable Messaging - Pivotal Tracker</a></strong></div></blockquote>
