### ISSUE TITLE
[Epic] Light Clients Support

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#6905]
* Project GitHub tag: https://github.com/status-im/status-react/labels/LES

### Project Vision
Add an option to use LES and ULC in our application. It should work on Ropsten and Mainnet with working discovery.

### Project Scope
* Have ULC and LES networks in the list of networks
* LES and ULC should work stable
* Minimum scope: Ropsten and Mainnet
* User should be able to turn discovery on or off (can in in dev. settings)
* User should be able to manage trusted peers for ULC from the UI
* User should be able to create custom networks with LES compatibility
* Low-hanging fruits performance optimizations should be included

### Project Tradeoffs
* Status can provide a cluster (or a fleet machines) with LES slots
* ULC can use Status LES servers as trusted nodes

### Stretch goals
(maybe) ULC patch is merged upstream (go-ethereum)
(maybe) LES fixes are merged upstream (go-ethereum)
(maybe) Background App Refresh on iOS and Android is supported

## Roadmap

Deploy LES servers for Ropsten
- [x] ~https://github.com/status-im/status-react/issues/5891~

Add LES/ULC as options (only using LES servers provided by Status) on Ropsten
- [x] ~https://github.com/status-im/status-react/pull/6256~
- [x] ~https://github.com/status-im/status-react/pull/6088~
- [x] ~https://github.com/status-im/status-react/pull/6007~
* [ULC] https://github.com/status-im/status-react/pull/6529

Make sure that LES & ULC doesn't contain critical bugs on Ropsten
* https://github.com/status-im/status-go/issues/1258
* https://github.com/status-im/status-go/issues/1248
* https://github.com/status-im/status-react/issues/6904
* https://github.com/status-im/status-react/issues/6901
* https://github.com/status-im/status-react/issues/6859
* https://github.com/status-im/status-react/issues/6840
* https://github.com/status-im/status-react/issues/6073

Deploy and add monitoring to Mainnet LES servers (Status)

Add LES & ULC networks for Mainnet (only using LES server provided by Status)

Enable discovery on Ropsten and Mainnet

Enable user to create and manage LES/ULC networks
* https://github.com/status-im/status-react/issues/6476

Add debugging UI
* https://github.com/status-im/status-react/issues/6530
* https://github.com/status-im/status-react/issues/6479

Document and Knowledge-share ULC patch

Make low-hanging fruit performance optimizations
* TBD

**Comment by JekaMas** [comment]
> Document and Knowledge-share ULC patch

We have some https://github.com/status-im/status.im/blob/develop/source/research/ulc_in_details.md

I can help with more documentation if needed.
@mandrigin 

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status.im">status-im/status.im</a></strong></div><div>Build a Better Web with Status. Contribute to status-im/status.im development by creating an account on GitHub.</div></blockquote>

**Comment by mandrigin** [comment]
Oh, that would be very useful! I’ll read the docs first and ping you afterwards :)

**Comment by mandrigin** [comment]
moved to Pivotal but low priority now, so closing this issue.
