### ISSUE TITLE
[EPIC] Improved Wallet UX

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6921]
# Problem

The Core Wallet team has been working on new wallet flows and designs that aim to significantly improve the wallet and transaction flows.

In particular, it addresses ongoing feedback user feedback and UXR findings around these problems:

- Screen is overwhelming: where to start filling out details?
- Can’t see fiat value of crypto
- Can’t enter fiat amount
- Tx fee is complicated
- Where is a total amount? Users can miss the confirmation details
- Transaction phrase is mistaken for password
- Place of Cancel button is not intuitive
- Transaction phrase is confused with Recovery phrase quite often

More details are in these wallet UXR decks
- [Wallet UXR findings](https://docs.google.com/presentation/d/1eJP-Hh4tN6XZREIy73GNuJP1LqGg41EvP5QpVlFZQ78/edit#slide=id.g3e1b33ca7e_2_36_)
- [Send transaction flow](https://docs.google.com/presentation/d/11vEgAbZgXvCwiS2QdMmW3vjOBApx5y8ARXNbFLyJBuk/edit#slide=id.g3beee3ddf4_0_0)

# Implementation

[Figma designs](https://www.figma.com/file/SIeZPHvrX7KUwEBW8VQct8C5/WIP_New-send-transaction?node-id=0%3A1) by @denis-sharypin 

[Epic project board](https://github.com/orgs/status-im/projects/44)

- [x] Restyle wallet transaction sent screen https://github.com/status-im/status-react/issues/6815
- [x] Wallet main screen restyle https://github.com/status-im/status-react/issues/6786
- [x] Wallet setup restyle for new wallet flow  https://github.com/status-im/status-react/issues/6718
- [ ] New choose address/contact in wallet send transaction https://github.com/status-im/status-react/issues/6843
- [ ] Extra: Crypto to Fiat on Choose amount
- [ ] Extra: Max button on Choose amount 
- [ ] Step 1 - Choose contact screens 0 implement in place
- [ ] New updates on wallet transaction sent screen https://github.com/status-im/status-react/issues/6936

# Future Steps

- New UXR testing
- Improvements based on testing

**Comment by oskarth** [comment]
@goranjovic what's the state of this?

**Comment by goranjovic** [comment]
@oskarth wrapping up and merging this is what I'm currently doing - https://github.com/status-im/status-react/issues/6843
