### ISSUE TITLE
Expand contact management features

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7234]
Update contact list with a button to add a contact from there, search, indexes for long lists and editing

**Comment by rachelhamlin** [comment]
https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A3116

<blockquote><img src="/file/TNCyHKtR3sx5EL6YznFWUa4O/thumbnail?ver=thumbnails/059d3123-70a7-46eb-b8c7-08b393783287" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by errorists** [comment]
I'm linking designs that use the current profile design, since we may want to get ahead of core and include contacts list before the redesign? [Figma link](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1606%3A12561)

**Comment by rachelhamlin** [comment]
@andmironov @errorists so [these two screens](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A3116) are how the profile should look with and without a registered ENS name, right?

![image](https://user-images.githubusercontent.com/15470435/51309051-d75f7880-1a43-11e9-8ebe-8fa6e90054d9.png)

@yenda is the ENS display on the righthand screen possible without reverse look up? I think it requires user action, like we discussed—to explain on Friday call with design. 

We could do a partial profile UI update along with adding the contacts list, like so:

**Expected**
<img src="https://user-images.githubusercontent.com/15470435/51309777-73d64a80-1a45-11e9-8ba7-4918cc4adc09.png" width=250/>

- No `Language` and `Privacy and security` settings, as we don't have those yet (Core team)
- New layout for profile image and display name
- Small new `share profile` / `edit` icons at top
- ENS names & contacts separate from `Settings`
- Icons for each list item
- Perhaps include `Browser privacy mode` "above the fold" here as well

@andmironov do you have a screen with icons for the `Advanced settings`? 
Is the `Log Out` option meant to come below scroll on this same screen?

**Current**
<img src="https://user-images.githubusercontent.com/15470435/51310018-f9f29100-1a45-11e9-97e7-aa70e92d5178.png" width=250/>

**Comment by hesterbruikman** [comment]
Update: We discussed work allocation for Profile design accross Chat and Core (with Keycard working on an update of the contact profile view).

Allocation and proposed changes in the notes doc: https://notes.status.im/wsJKmUfCQq6_JlawUwabFQ?view

<blockquote><div><strong><a href="https://notes.status.im/wsJKmUfCQq6_JlawUwabFQ?view">Tech review profile designs - CodiMD</a></strong></div></blockquote>

**Comment by hesterbruikman** [comment]
@errorists wdyt? Looks to me like this issue can be closed

**Comment by errorists** [comment]
@hesterbruikman we can but bear in mind the current contact list implementation isn't finished yet, most of all it's missing the button to add a contact from there, search, indexes for long lists and editing. [Figma](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A4233)

**Comment by hesterbruikman** [comment]
Issues (to be created) for this epic:

* [x] Add an empty state to contacts list #10891
Issues (to be created) for this epic:
* [ ] Add search to contact list #
* [x] Add a button to add new contacts to contact list #10892
https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=510%3A4233
* [ ] Add long press menu to contacts
https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4067%3A74
* [x] Add UI for adding new contacts to contact list #10892
https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=3767%3A21111
* [ ] Add alphabetic indexes to long contacts list (low priority)
https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4400%3A25384
* [ ] Add list editing to contacts list (low priority)
https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4402%3A317
