### ISSUE TITLE
[Wallet] Epic

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8028]
EIPs
- [x] EIP681 https://github.com/status-im/status-react/issues/7325 PR https://github.com/status-im/status-react/pull/8004
- [x] EIP55 https://github.com/status-im/status-react/issues/4959 PR https://github.com/status-im/status-react/pull/8029 

Bugs

- [x] No loading indicator if pull to refresh on main Wallet screen [ios only] https://github.com/status-im/status-react/issues/7812

Features
- [ ] Ensure failed token transactions are shown as such #8153 
- [ ] Show values in the user's currency https://github.com/status-im/status-react/issues/8027

- [x] [Wallet] Custom token details and remove #8236
- [x] [Wallet] erc20 custom tokens leftovers #8243
- [x] Basic user added ERC-20 support https://github.com/status-im/status-react/issues/7983 PR https://github.com/status-im/status-react/pull/8235
- [x] Use newBlockFilter signal from status-go #8159 PR: https://github.com/status-im/status-react/pull/8158
- [x] Use status-go subscriptions in wallet #8151
- [x] Per#8152 wallet transaction (includes getting rid of the limited transaction history for tokens)  #8152
- [x] Sign transaction module https://github.com/status-im/status-react/issues/8026

**Comment by rachelhamlin** [comment]
@flexsurfer @yenda looks like we need an issue for fixing Tx list? https://discuss.status.im/t/proposal-fix-the-transactions-list/1190/12

**Comment by flexsurfer** [comment]
@rachelhamlin yes, I'll add soon

**Comment by yenda** [comment]
@rachelhamlin @flexsurfer I added:
- #8151 Use status-go subscriptions in wallet
- #8152 Persist wallet transaction (includes getting rid of the limited transaction history for tokens)
- #8153 Ensure failed token transactions are shown as such

**Comment by flexsurfer** [comment]
Great, thanks @yenda !
