### ISSUE TITLE
[Profile] Epic

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8068]
### Done

- [x] [Bounty] [Profile] Other profile screen UI https://github.com/status-im/status-react/issues/8071
       **Features**: better UX and contacts prompts

- [x] [Profile] My profile edit and share screens https://github.com/status-im/status-react/issues/8069
       **Features**:  name change restriction and better UX

- [x] [Profile] My profile screens reorganisation and items design  https://github.com/status-im/status-react/issues/8070
      **Features**: better UX for profile screen and subscreens

- [x] [ENS Names] ENS username and name verification screens https://github.com/status-im/status-react/issues/8066 
         **Features**: ens names for contacts and chats
- [x] [ENS Names] Use ens username in chat https://github.com/status-im/status-react/issues/8067
        **Features**: ens names for contacts and chats
