### ISSUE TITLE
Status incl Keycard test findings

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#8253]
Status build with Keycard enabled: http://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190520-120558-5b5a7a-pr.apk

Compilation of test findings. Individual issues can be created later if needed.

### User Story
- Setup Keycard
- Pair existing Keycard with a new device

### Steps to test from (https://github.com/status-im/status-react/pull/8097)
1.     Set up keycard on device A
2.     Add existing account to device B
3.     Enter pairing code
4.     Start importing account
5.     Account imported, you should be able to log in to device B
6.     You should be also able to log in to device A

**Comment by hesterbruikman** [comment]
- [ ] Have to scroll to button "Begin Setup" on "This card is blank" screen. Unnecessary. Investigate more efficient use of space > _This should be resolved in updated designs_
- [ ] When Entering and confirming PIN, last bullet doesn't turn blue before going to next screen
- [ ] Codes require use of SF Mono font to distinguish letters and numbers > _Should be resolved by updated designs_
- [ ] Required to Enter recovery phrase. This doesn't align with Overview of steps on first screen where step 5 says "Backup recovery phrase. > _This should be resolved by the designs for Recover Keycard flow_
- [ ] Validation on Input field for mnemonic shows "Recovery phrase is invalid" before 12 words have been entered. https://github.com/status-im/status-react/issues/8144
- [ ] Error upon completion of Keycard setup and pairing: **Error** java.lang.IllegalArgumentException: 16 > 0 https://github.com/status-im/status-react/issues/8256
- [ ] When pairing the Keycard to a new build, the validation remains 'stuck' after a first wrong entry. Showing "Invalid pairing code" https://github.com/status-im/status-react/issues/8147
- [ ] The UI for the recovery phase on the phone doesn't match the UI on paper (columns to rows vs rows to columns) > _New designs resolve this, but they haven't been reviewed and are not ready for implementation_
- [ ] Last word on "Check your recovery phrase" should have button Continue instead of Next
- [ ] When paired with the device, Keycard opens and logs into the regular Status build instead of Status PR. Not sure if that's supposed to happen
- [ ] Setup screen is shown for a few seconds before Pairing screen is shown. Do we need a background screen for the time it takes to detect Keycard state?

**Comment by andmironov** [comment]
Closing this issue, the findings listed here are addressed in https://github.com/status-im/status-react/issues/9264, https://github.com/status-im/status-react/issues/9274, https://github.com/status-im/status-react/issues/9277
